proxies:
- name: Americas-01
  type: http
  server: 77.111.246.24
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.43
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.16
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.10
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.14
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.160
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.233
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.77
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.58
  port: 443
  username: A615AA6BF7EDB4DED52A3BBB47E88997D125157D
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJZ3ZyS2R2alFGa0xsdGx0ZFQ3b1NVOGRzY0lMSkRDeFl1TVdVNERXbzZjIiwieSI6Im94OWVLLUpmcmZBRDFMSDhybFBuZU1ldzJJMEdQUTdkNkxLVlJxMXc3TEUifX0.aawiQcsaMUG4gVcgE4N2IG22eM6DYKhBqmziYibwHTaRwLdbwsZSvw.DSZfDRxhMKl0FPN1.g77gt9BglUPrEy80tpeZxiJbAP4grF1OMqS2zPXfP72rq0n5nit2Lyj9i8JQp2M-XhWJs7cBIp9xHBMcQSNpmGt2PUUjyTkggEMh73iIA2jvwjL08LDcGi_p4RBV-7lcsIpZBu24AU1fwSNEQZBMtNBzCibvO6ESMJd1o-Bp3RXijQkwcCUrXn7_fU6VP3F02d2LKS68ZtFATLDMk1uNUDXmhkXG7knsMCVV7RS2xi7JRFW9KZzKvmlHHm4qe2xMBijU95RYMzbHGQG2BQnmOhjsn-ZuZhyYtfbosGyH8NAWB8-ye6F3uuxt4xyhqqZoeB-znMtAPilq_XSh7CRQ0GV2M2PNVK4g0eShR8oJcoI80moQ-fKAa-rZna3Mzm5uKXrN2LpK5kwb6tNJx1M2xaI9kXV1g0NMg8aIB6iVRRRJC570ktuZpUB_djbiKgsCP0KRm2kinlXkzqE.TnnO-kXni-lEJEij5gqu8Q
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
