proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.246.41
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxT0QyckNuUG9YWHViMkZ3bmNmeWR4VmhLQ05YUmlXakRzT3IyX3Q1RGhBIiwieSI6Ik9FbVlDcENSOEdwQmswM2ZFT21QZm1mWkR5Mk9WMDFGeDl4Zmo3cEt5V1UifX0.Gw1opyMUBfrK2KElTrvLocOOrzXvx7yUugMEYwwUwmPv1aCUjRVzGQ.Yo5TGF73N5y9IBCO.a2llHohH4EcWXHPaYOFpvMuOmuujlwwiwVK-j9ppSoNuIt2G6GwRRolp1ZJcaNb-pnBc7Tg87kD1jf6aMFgE2s3yZSkrTwQ_4ado7s4ZB_Zq4mOyEjcTSREJo2ZTkPR5t4AVbLsvCPP1HUu7dMbx7dGn5e5ngNm2x_gFf6c-jqth1YP7VoSpc5HRTE4g_oBrRfjT0Gqv1Qjni7fGgRYk2RYJGFw8p-E3DzV0fqPrJO6XltDgA-g0pEJ_oe_0eXZlvVRw6F16jyR9_v1RV2izTmF0DKt5JtJIr2lrYmYLZthoeE2sJgP4Y_r0bN4E54VAYxG18A63-BgiQtHPUZKbYtGAxOzfwgy70UKFC31ZWkC6ZIUQpbqHScscY9-puVQv2AByaLFzNDhdDolDmRULdwQifWBjAkup9R6tEyzh51seleCw2qYJ5-fuxKrJqBS33j4vJl4phCM.5KqQ068p6SA7WUhmX5QghA
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 0D34EC5BB6C25B64A6FCE2A622626D33960A27B3
