proxies:
- name: Americas-01
  type: http
  server: 77.111.246.22
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.55
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.126
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.60
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.14
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.15
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.11
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.12
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.147
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.224
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.244.209
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.76
  port: 443
  username: 489890A95D04C0D71C1B8B7FAE08656C6E7044FE
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjVzRUWnhYenYwUV85bzE5Ti1NbzZrYmhTM0xyU1dYMDFacHlsaXBRZW44IiwieSI6IkNmUHl0aTRWcmZSSUNya1Y2Y0Q5QTFTN2Y1TDE3UTlidjFKZkpIc1FrYzAifX0.muFiCkN9iKzgKbIC1uccYWUAnKBfhxz5u9fP4zxb0cm9pAYQ4NoChA.GB8p-R4T4RZOpx9M.ibZO3n4My9JgnThotBRjrcALGxoFiVW_ZKXNPltAYRlVXmtdCLT7K-m3T4Gglv7q13v7TOR4nYQ4E9RZ3PGUzPw30ssni3aMKAXcVvFyIV-2309NgOx12jTvCGwf50dkzgFmFmepJJa3EcL1deNWZkDrwRMbB17DwV2iItxX5L7kLkp5NQ8iWpcflABPGNJQ5jaXN8cd152cZt8VY8nRJHMKoam-0IM1r4vQo7PvbGxWPgyUO9u34lGixKCJucv-3b0L4-wabD8614KEVh35sGxJ7-4M1PG_IARZDW-lmBFD7z5N1Hpnm0dr0-gepYiVoGEP20F42lnQd4bPZY1sM9CN3NuidYk7jTJLslB7lkxVD5mi7A-DUjqhJNIUA81FZy1JCuYsIag1qt6T1yg807lQXS6keNQA0FYDugXk5QwzL0CHfsPc9Uqyj-kUAwpIcvsRjC4kNOtwaro.umF5ZoNqZMlpa1TDYleOeA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
