proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.247.22
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.247.128
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.246.21
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOb3BFbWJPWG0tMWxBZmkyNVhSNkRraGFrUUxpeGRuQUstUGlRRnFRd3JjIiwieSI6IkZEeEk1RUZJOGtMYVlySG82WFd1SEN1cWo0VjctcnYwLURib2dIWHh4MkEifX0.5J0pLEO5rOYjNuLTc38_duj_BBFNzyJbfZ5RMCvQSDwgNfUrpyoeaw.RMVTJsfsy2QkZ-zA.KhwaMD91OjN3aBgkVRCbLiyGQ7sq-RwuJGCT3sOURGQ2IrgFNSdcFyl0DXWlqWgYgQT1N5bScvw1oAnLwiRCjx8m9LygODlqm1nT1s327WlqM34vhK-PXC233yaasSk5j8-6Siinh-Mk55_caZ0gE62U4w2e-LPuc5Hs3uEDmvqqqCfSSPylWOs0yZj49f0_WF2_YWD8dNn_oZztP4AH9qqCpllabW6SoFm8HH6YSzjcmSygidYDnzegcRA7p2UzvdXdL2HQN4ZO4l9uhKieK_P8VpGSAwyTnTcGClIgO4KtSqnB7Uo4veexVqnKPockHpvxh0mGvgc2OccX9oLHKlXJR7IDHf9BjJzhpQ1rk9ahtaWsbev6AZhcGxiEaL2X4tDGP4Y_hQaANO5nJPVWzJhpUGjVqEhFRzHcmRF_Icsy3DUqFXuUx7XOHCO4L6GHEbhimDDR3YgS.ahhKGWw1rrRCK5h1FCC91w
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 850B150CED3606C8708C0EF5F03D30999E675BE3
