proxies:
- name: Americas-01
  type: http
  server: 77.111.246.25
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.47
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.61
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.16
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.15
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.13
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.60
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.117
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.57
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.76
  port: 443
  username: 56FC7F770EF6C08CAC4D80B64A371462EE47BE7C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOUWVSczZsWlBVMkYwT0JxU1lkTGtmR3FCcHoxSHc5ZElKeVNyWDhOOWtVIiwieSI6IkotMk1oQlJ3RkJiLS11alFmNzluQ2lfSkhTVGt0bFBqVi1ZbV9TU196bkkifX0.entpW5lrYcKIK4HV3GYhvXwmhTtmSWUiydQ1LlUVhvmj09cuHFlwqA.7YNBjhwK-Rt3SSTq.MkOTshzUYFFm0BTJwjd2QNNLhT3aSFmUGBECgrZTNbDGCGYzG-W7HvC1sshmIEJImY1PHvDAWjWp4Vz2FV96hlbpmh53vRTkXWX26Pa_jm84AeWtRIYbvRLqZras1nmYFQd6iWIlP5RNq0Lin9IHQu4-TVL9AAwEFMiPbki1Ug45tSZki4tP3qcd1IYCYq3_hvq8Rxkq_3vGf3rNYsvROur_A9P--3xuCemC3sd_SOVTVwtRSad8YliONYczA5cH-rYWf_WboKTdLW1xxmjle_Gx9SQZRxIuaA3I9zyQd-5QUCZi8g5vjj9taRrTMJEfRZptaNroKIKmDSDHyKt24cnumpBdiZTMN1xfT7cyqQWbl6splEIwu2i4NYzvgQOeUROgr3PaXO8QNPH1ao0lQJc53-cePEQ1HYXl2ehqaEnAVJLRUvEJojfaJE4gzNNW6JVzRNouRQ.jm92ttkFXNKWMt3S8dqjYA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
