proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.247.64
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.246.19
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzN0dGR1c4dFRuTDJPV0d2ajB3d2kxSTRPNUNUQ3IxQ2tBdkZ1QnlxS0xJIiwieSI6ImY3U21rQzA4N09OOS1la0ctN1BrMTlFTlltaFlVSHRQZjduVHp1YmpWMk0ifX0.D4r4moENyfjEJFLc-jjoPzGhedwzj_LHgpvJ3GEL86GEf4t16qaLBQ.eocGXJE7LmI6pIM7.ISlNGwqIfWcGXb40vMpwerQ_lnPsXILwWaCebWTAPNB93_BnDZ_vzAsKwekmgIiE-onbhfTgxwRxVUQkCeMyyHJjdcODPOD6oP-OdZNXCyXivjrtZHmS-9noc4OuXYtE6uMF-G7GWKCMDvathhcV4fIxc53RRto95neODAdulO-Q3O0blpGTe7pPAyof_TZiCHsgtWkzOshw-KKKoPVzDfAiF2ruIchUGFf-NyAtMoFaNzbDCyr8QTfZIZD0rZSWVgNECbM0Ee0eZM7y5xzNCxQ7yqKGGHJizSZDQRvbrOEKNnJirvuxYxMtiUVb3kN_Faraq7iUUEMQVefhq0WRY46N1-PjNOUp3Qf3NKMgITgmg_J3MMc3xm7g-UDZRc9_TO7snl1vBrhal0VAQ8EdHkolZtOM1g8jjDPnpY7gN8hbp-ofjOv_U_pkGsTvqBpjS8GSYjAB2JeV.eR4m3asZgQbZ-nvWiteeHQ
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A3637CFD73D2F55E81551DF5B0447D8D6579359F
