proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.246.53
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.246.58
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3c3FjelRXZ2NINFFDaVlBdkoyTnNPQlB6XzJRQ1A4R3U3aF9Ud2FxbnVFIiwieSI6InNuWjRlZ202cEdicUdFQk9oRENBQ2gtb1ltQ1c4TkdyVlBVaGZLbUNaeUEifX0.rHTnEJHRc6-hScHHsVsbwXro2ayDH_KlFs5xj8DjjxzbIHtDRFPoCw.sLDOtIjXuu7UIIKE.CHZRAszVUPVSNcKTb1lBPI8Oh9rM0Uf2GryBHzEvim4kcJMjlll_X9b9d86UVyTiPf3yDQicsWddMNS5Ei4xfPwTk5o-SrCoaaWGAEkMdibklZZdrBb9cku3isRvjjtAGCwQUQDiTPn_NtYasErK53nkxLvcQqanmG0w1pXN914NChSfC04hWOitusx7y7s6eZgBg-ZvR3vgS9xWvciTOcnSnjM8RCsBnhPoEgJDHRj9cex52T2p04iCKD57DebDE8_1dmAz3IeBgEQa-JVQ7rT0aQnP-rkuqz1VMNUqC_gEhoh2dwcbiC56VTj1s4A46Gd_sE1UIZlDCuLPAzcADu0ntlqhqHJrKvcv4_z9Hu4nXIoq9tf6x1U_qlbdheGSOBEMr5ofC8mMmXBN1pd2R1ga72pKm23qF4yDXquStT5FTFFAkeSH93fzq9EuP04r_dKIJqVwpjA.S2aob4EM128l-epXGR4dpA
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 70529287DF802F3CE93504FF88D6633950279AEA
