proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.247.22
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWNkE4QzhXUnNDWUt6TUdjNlRXeWx2X0NSbDIzcDRJRmV3aHlOWThtdDRjIiwieSI6IjhhOE80UVQwb21RSmRGTHI5YTQ1Y1RGa1Z5Z3BuYndhbEdpOEdzQUFyTncifX0.GBp7KttcO9On4Y97zRPB4-inNv4w70PspXVKV_hREqJ2N4VUXtrIPA.cEka5C0lQCAB0dcE.u7GoMY1lcj7caQ0AZ4z85AslxacKOSbS0PcEXGYkIU8k4Y0z4TxqmKQnXKFw94--UNEeWDFmll3ZLdREBhNj40xyWtbuCzt02Bsc2OKPuLVq7fjyt7jaRbc_0QDPh_bqs0PAuYDB-mQHH3cNBxFjd2JPvzAZn_FAiFVLwNiBh1ONI7U7IbEVwNHQbI8NIr3mHhaTgD4fVab7O7qyRBJI0tOFFuByToLxP4GHpNF2N3sJfC-__vAeIt0Gvr194RfBLRIfISlCLZateWrwmzdRNH83bLivom1hcDFBWaa2JeN_PNjA1NNuH1GOjDb-oEbAZBbnhDN0TickOvJMzf9b5ytV9yJ9xBQWo8Q2wgGVMK2qbGnKgD6EojZkG4IWbeGepg0rdg_xnETg42I5vTt6CO3UIbzxU6zM1SRhvyFJ1V5uamUFf1EBMyKp7cw708hG2pZzLkrjNakV.NR5EXyVfe4svrSPUMo7B6w
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 07DF5720163952A15C77DA5E987B19800E1EA560
