proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.247.206
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.247.185
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.247.147
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.246.19
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.246.33
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4d01fMlA1OVBfUGZZSW9oUEtVLWN4RWRDcUQ0amllS2lSZjNjV2xqcjVNIiwieSI6IkQyc2piR29pN3B3c0gwNFRWMHpuV1QwUnh6Tml6eUFaaE84cTZpSVFLODAifX0.spAv7guChvHYmKI0Fn7e0t0DsmPtetI_0OwDORLu4SMJiar3GGGQYA.I3Gy2RaTdiBIWlS8.M7S9JBoREKN-l238Pzi2bRY0HGq0eudMHnuQslyXn3jEzkiuoRS5BRdbzteYA0o1dvglKRDQLjG9im-v4pog-vTK2AZh2tUnts2hUOSq3iov5rFd7lA68hCBdhquFh301uDaArVYBNG9YnJBxwoxRm1Pc2zoPyGLYNCcEIvxS6ieiYwKm5R9RN9H2Ptu6WCkYJgulZNLCsG7iObFpBMH7aHH2FI4lSZUs1JUd-fQngb7Y8fCphhEKmkdhJE3zO2BGuku_m6ZGSMvgIhkwuoUdGmPGieknCRe7sEvoQ0LCIZKDSgyKlpS53ZShxhgLKObl2mb1O-8tdeiHLcyPto628Q1XUHrLspbwHICDJv0rZ_Lg7GMh2P-3Km7lm0HvZdn4REsWkiujX5ZmqU_y8hfe1N9u8LMq5bfM7RYthnxdKMvJ2FJXZLqt2HrOaUiH-5HBdol0T2xRYw4.2KCO0B9JpkWC1rGZSie9ug
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: FBE09D2109B3D48A757504816C4863AAFF381976
