proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.247.129
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.247.117
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.246.17
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.246.44
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJIZVloQUw5SU5pTWI5azJGVHIxTEMzdEZUOU14dFFIN2RVSC02cVdHZXJnIiwieSI6IkliRGdSa21UR2gtMGlnSHI5azFhYnN1cHlXblVoSTg0ZTl0TTJVYTEyZlUifX0.wcGwd0mQiGryKZUDFs4Af1qbKV0M7UhYvmJixDKqzK8elrW8LeA4hg.LpHiD_MdXswfYdo9.Epml-sQkVplAS6B7GivphNo7qOeo-JzlxrnuIahkBZUCdm94qCMyL8no7WQivR1LzOxjQHxzPAsCmFBetCgeXthEQVNuUhI34FpQbqvBS2DwzPy-TfV8-cglYQSdA8BDvAmjjS_kuStR7ftCq5juyGpd12LcrKb-NSIYjXL6NGGR2UEEB7eodz58Bu8u6a_7UuXJgA-8Q9lFynRPFYj0uou0SBJWAcYtO69TWzTip6xAcdcqKgLUx0uah5xMJ2OhpQGO2ePNWYig_7-5jwKR4ZbeLCiQYY-gq_zxZivJa2lzmTBEbC9a5k81UbfH_KoN5OzrV14K1d6SkAOPc1O_ChdtXsQkOFlVKK8pWX8_1Elo3ahYPoXP_Ex38Q_3LRpOr2CNuJfEWeA-5arJUg9OXC3F2GbGJ9BQWS1y5LMUKQknjw_s3XCKf56Xr0m8LBFy5nrn9aeSC4Q.Iz78wIsdUpXmhK2yHT_0eg
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: C121D6BA9EE117F8AAD2C95DFC293FE92233B0FF
