proxies:
- name: Americas-01
  type: http
  server: 77.111.246.36
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.49
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.26
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.10
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.11
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.15
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.147
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.59
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.67
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.77
  port: 443
  username: 46A47F6FB516FD1497C769601B8F17753C0E9833
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVeUZTN1dzQ3R4OHdoVmZDUjBPdkI5WVVwd2d1MjlseE85eTdfUTdGaHBRIiwieSI6ImRCeHNkODZSLVlEYlloTENMeXNOX0IwYVJCc2ZkS25aOUZaQmFLd2ZQREUifX0.ddI0gh79Ez_0t0v2EFUj-D6glx5zjx_T201iN03468fkBkHf_LUuXg.XU0CnJ7aA3mXP4TM.VxNwFSwvHbYsEp5kkveJQjHRoppqZ2HanfaGYWljiUlTuOQ46vUp4h_y2B8FP3ck2dmtpbB0CfBMXL9IynZ2mZQZmDvkYWaONRtE6RkznhPVjYC_Av6MAPIcpXADb7ZGty9w4jYq6WANSQfglhyuk4BQZRZiXZqWYML4ENaYcexgMySobfDZ0ws4f9imjt_CKO67PVhEGEmKIgez0z0nDIBaHtdLU951NcD7RIW73q3Q2N48cXZsvFWfWG_RkYATX5h1-_sZR1t38kkeUfLLhlNvHw4sPpFQ_mbD71olGdLgq4c9jvKij0C7u9vxWaQ4-j5RwY2tthD5t4B4DE7mMa_HLkzBHZy_U4PWfo-b-qJhvdxYVq4Bmk-5FaOgzB6mOVpzg5eFfHFXSTHoFUna54kjaL74VmUGZE82bu-fFFiOkT_PlpxgiJvLwuQaD96_03PR-RAqDGg.0LhVxB4o0_jcUrF1AqHKgA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
