proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.247.128
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.246.42
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.246.18
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJzRzdnS0pCcWxLVWNPdDBSRXJ0VTBySTJYY0lFZFI2bnB0Q2s1R2lFZHkwIiwieSI6Ik90aHhDcGFTV2c3YWRnbEVsck1LYVJXMi05U0xjbUtaLUdYUXpObGRxTm8ifX0.wgLrJPFdqRqgPTtjko34Wkv228stHqf6zSMr6UrCeHY5klCO4Wp4Jw.AlHLs45lXEjlrj7b.BQQHHxqFT-aRQDDVq5XL9WY3QbhSAdYZtXJBHB6u9-KLXE5jyUqInUBdRwopfCnjY0IczbsUkUPyK42E8FWNs0xQJzPp_3nlgggK1ot-osS0UFYAC1s97QNigfuJFCZPvy7ttRr0y477yoMu_O_g9oVnUpi2HVHR6wefV5Lm_BACPVCU8f57zWUqX2TI-WwyK0fLPdTrNmcInLQsfP86JfwzLBpZ4OKa9B8ruiD0oFccVtSZRP5YBIVXblrDvQc_ZFyfQVa32TWaMVi7j4H9Lvyt7oeLT_js7oYcBU3jmgdaL8Hqw6-qC-FCPtYcdq8swxEytDjZekVXvEVYLBuu9Lf6I4O8nAAPfCY86rEzup9ZbVo3kdzfzlQQZP34ZZbs2kDBTN-ZvzFEBv904LV3XAjvRBio4W2fQKnhQaZBpwUNak78Eh3JkpGNxVZ1QIGGvLOQyBWK5w.n24GWbMMDjkQKn6KFTr5rw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 354F56E5F4B3F76C3A41C5D127496E349C53F544
