proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.246.48
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.246.42
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2cVZ3RGd1WnV6N2NXdmVpUGZ6cnFMWkRObVlELTNsdFBfUkdNOW1KNEVVIiwieSI6IlU3WUJGc3dzUDd6ZEdqTVp4VjQxZ1N3M29sRWFHSlA1SG5NUENtbjNGc1kifX0.S6XoghIGnjLqFEub7YDW2sDm67Olg2Gnhxmg9ubUT-XRCk9jqJv30w.YBfxeuXP9h1s7M39.QVN-p2I2tomzM_uQDRpQYWn2jXMHJ6Jw15G5DdMzOLy3fZAbqE1OzmB94eqdi5cT99CuyRTnNuR7Jg8s3lMacLcyMeQi7hgRNrAQidphZut6KKUEhoR8iaOdkp7SzUZg9XrFgBt86XrkTxY8UgD8QLDbIFRJghA4Qk-IFJNI4JxGn7bwyRJ2uRPRAUfFlK2g7LYlkuSWssjfHSWj5AK29Wvvlq4HXGEyGPHzsjt1EE6qqHTiRTT5lKyJ4rLNxpMV8WxXZ1Y5UV3v5DWNQArzDFn4RhiPwN0hzsXrrdYheCVwjO68pmyHuoTtprMR6N78hypUXThFL5L2JpLs8RXCtaZmoAkbH8Y1ygaaF5JEbYNUtUoB64Jyayc-n0gEecSbxnJg8f7rI2z24chkdYk00dg8FWnstuQKTdNCyjpDBO3PNpx8V8NYjztkNbg0lbG6nuC8Qw8oYk9wuXk.m7QvmMvCFbP8Jp4vxx_IxA
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 8657318AEC987E81A6AA20C1D1DDFFB9D91EA7F0
