proxies:
- name: Americas-01
  type: http
  server: 77.111.246.40
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.24
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.11
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.13
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.16
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.14
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.187
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.43
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.215
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.56
  port: 443
  username: E6A2E4591B2A47097F93756B9A7E63B605D86DC6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0Q0NESVpTekM4Q3RuRWtXa2QzaHRLMk91NVRUZmo0VXh4QkVkSG5aWnE4IiwieSI6IkNfcGRZS2txZzRWbG1yaHFCemZaYVpNdFh1YzNOUjltc1ZHVUNPREtVbEEifX0.CIJh3yH3cCpKN6Vgv9DgifEqVzRzUHrz-OiXlF6phkrDgatKAfMKgg.5BEyNerU_N68NMFH.r2zpJ_bDqS3pu6_FCgPlPQZlNBn8TLu3-GDMpia9sNobD8lWnl2ND6rBXAizbEzWDSPXPcO05JBoANAyclr7n9eFQEn4ctYYXpBZqL7TN1gV64NrKVY2aSvL1wI8G7eybb0a5BzaVPTOZzizyGb4HSUrI99VP9UudwKggUjLhAMDi4UKjIrJAmIXFMk_VpDXb4XLRHC1BI1C7A7eL91SJwPSvdRtQRRvNcIichQdfQaKVU39rioDKx3jFd1d1CS2Sd93aTHtycGFyNjQLMYDrKhio_HSFaOvVEN2SIjIl8VWA6h6XbVV-5t8-vI5GJCILLk3JmACYXA90GNrplDzNp17U1Dg6jP-vaCX7dlRSAmOdK_drd61mi_OluLJBPA9C-TkdAJCStOy4GO60HAJVHhgC61Mj2RJqJcohSv6n3l0IxZpkwBQZAVEEfsni6ewRsI6cs00EQ_0.hZcdtVgysy_rzWlVx5Dgqg
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
