proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.246.10
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ5UkZOeFplX0F3d0F4Rm1HUUctSzRwVlNMbWcyUXlTRXFlRTFLVzhITGk0IiwieSI6ImFua0hZQkpldmhydjN6YjRNT2dtMFFFZFlPZlBvLThOVWVKdzVBNzQ3YlEifX0.cNorzXc8TXt2_sUwo4PG-VMC_9Ek0qDibDrQsL7ADZF0Z7hXvcOXkA.td_q_GKDU274uCrH.ZOnsb3BYOq7BrJmHpsaGyA1RA_EltvL9A1BIpftoAPMTbRhCMwtRpPCkbCZ_hVoNj0W432lM6jcPtS8NNutlfM8Yp6PxOrk5Dfq6GeW8A6RmQHhn6XxB2rqoFbOrzUPNytQ_DdMYpJu70Ss-Tp1hQbH_1PH1wf_gwDTYUMj6llkBqn1vf-UZNPrW6Y7rQ44LwdiI5VaHXDhTIAWTqlsW8N158Fi5EcYvhg_lHXzlTFHQ3d0oope5Okjfg81oWtyp274-8nfXqmHUv0Omg9FJQAMCL1Fy2eYGSrFxlVYXu--bJK0l8CJ7_7nk-hBi8WQqGscbU1AVKaw8TfTC7Rv9oZ7fowEDLVAIoPh2wg24Wx-JtBircWV3WIA2OiqK11RoakxOimW8MMZcxcS_u30RL29R6lJtj8yHmr3__iFHQSv6FG2n9v3N9HHMgArAlt7Yl8Sb2MMVupEO.V0fYAGQ_Q5RQz2lbTKVfBw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 5DB3DF39C14D79D6AE0347930CAAA0049B39A600
