proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.246.36
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmUUwyTHo2bHBpUGkwSlBMaEI4anYwX1BwNjlnaG9TVnpHZG92TVpmRnd3IiwieSI6IlpVSDZDQW03S010UzVoMjB0VU1xcTBncld4LTFkUjM2MzMtNjZoSFN4dDQifX0.hXZvFlJnhG-Ha1LUot0v9-vTshgjVtAStev_bRK5g5srO9j0x2aexg.7a8obP1gAxRm8hy1.ENg09bDOe4XwgNC7yPsSUdpjROFXI9oUjpSx4U4SmWZrBNltZy3ESeHgIW4cMCBqTyT4hjgp1Epxwa-IwK7kTSILbgKrHZix-2ptlXXVQdtF0Ux_uS9bYAPxKdrKbQDxhpQoyaKSSXKMBvpus3oSyXMg7_-Fy1cz33XAKgo1OUTLW5XgNyVK5VIbveGBlS0ObzoCdQAgPGWgfo7PwdyADQQ_78UaHPzng0FxrNh7DyV6vcGE-CI2uTYmblcufjxx8Id3p9K0-0sjFvldZoF3ZDfxylRct9e4FF3yt_K7ek_fCpMB_LrX1ix4i6RgAnH9CVVshazvU6zgKxKLE0OE-tSM15SJU15nVb5uR0CZqLHtcgBFslCfF34ebd_UtAFc3R4lzoTUa82mC_l2u0r1QRNBiSp7x6TZIJK0wyLA7R9Y-6fwRBJ9rAZIuU07zLbKi4hFMNZjAHtGx3Q.bggZtuZF8_4bN8FrUDadzw
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 11D34F3A5343B6793C8E8770314F25BDF0307448
