proxies:
- name: Americas-01
  type: http
  server: 77.111.246.45
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.48
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.26
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.63
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.15
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.13
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.14
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.82
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.43
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.72
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.46
  port: 443
  username: 826BF89A77A9619D61F6116DE269A6E95FB78EFA
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWYlJ1bUt2OUVjU05RcFJVNVgtQTNGbHNBX1RfU0pNeDRfQ1NwNWI4SGtzIiwieSI6IlRDQU40Z3Y0N2hRWHptbW50bzRVVkNUV3lISmJFeVQyOXUtajhlMVZ0T0EifX0.FfHnCbWxfsZnoetrax7bFBk_ydtLQpModIoNdO8vz5Lyx8mhpffBIQ.KQR6dULe8DJZjEGz.Kf4uSFlls86fnO3wLuC0TnUVYX0jz2bpuIQNTd4oNedhLiMkwn0tF_PDEWp5zYoJZgnYzIHZYNToBfnfYh4AFS45W_jJ4ZaPJsp06XAFAI_K0m8VzAJqx2GV-Hh77Ayb7kKiY7_GFgoPE_t05S2UDCvhX7F8Qn9SzkszopSFd36HaFiPIOuAcRdt_mU2wbQMTw1ofrpXAXlatW3Pu63bktirFrJzv0gRodjTP9dSK5skbMCHNGhes69waBnJ6V9DerimBPzJXNbuYA-QPupckE09Zj6rWO8GwLxI57Qcz7ghkaLHliJB4mCUExZynHFyNkfyeMywsL2P_c0B7QUYIHNxZNgw0dTL4z5XUf5mAF4M1PDnD-2zZwvRsbA7Hfl8tDr48076UhyhMoAENyLzQnJFEd5xcGmzUGr-Vzaz1qLE2N4qsv8dSHnnQ750h8sTTeIX1Xl3dacbKwo.vqvZfcvTjcgorNdJ1C-arg
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
