proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.247.43
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.246.17
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.246.45
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmY0ZUTUtXTW0wb2dHaTE1TzdpQWtCUG5LdldQWUZaa2NhaFVQc2xRWVNBIiwieSI6IkZQeWJILXhVUjc3UDhrTDByWGNtSDVJOERfVTIzemFfcGp2LXBuVnBaS3MifX0.SCDjvMiNhQWXadpyMqsrXWSfe2CDiKzXLWXVSGny-SWRGrxj9_T9Dg.GgCwp2V4XKV44uE1.5Xjtttqe72nZXIzRMdFhuZ2SKp2QmmbzEvGgFHsJsSjVdfy7PTPD70Ow6ngRQMOhRX9pmzmZl78pb0A-sBy0nIompWV6ihwZi8hVQ36DT102DgZ1zE5JWwe6pFUHBJ8f6c9UCpMnun2kJkt6zHFZCm2eRx0pzgbOp2GFS_YoYknbIZIQ0IjyilCdAs8domY4NlwoanZcjJeVtVY7kb3JcuIruvwrBe2z1DOReVpy1eCbZsSJPoK8Vg6BYtCxnsXzYVwWnqr_ihfoSM-Oly9Cvu6x6fUV1gCLXrCEHPMQK0EUYqcAKJq_tI7BnCxirwwo1F1lUd-1jPntdaZkUGv_FnBJMtBvhxE8g5wyyb7Ud0ZkyzkKYSjRNaEtqiokZl1fweEst0GfiZ1sJFElMEVkG1vK9lfXPa1ccvA3xbftCn3NQNzUdk8kqCeAHWcUPmN1MeafnLo.d_rMYvayaWypAgLex3BSWg
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 9835865886407D410D5CB0C7C19F908C5F1815A4
