proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.247.206
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.246.50
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ2RzB6MXZsZHhNOS1qZnFMWEdINUpMMnBZODVPcmlTdE5XRHVZVnZXOWtRIiwieSI6IkM5aERJQXdZNWk5aDFhcXNzdUF1R0VjeEVJMjU1Wm95dkZKdUpVZUdRSU0ifX0.bIuSXV44PorinerLmVDAjVIyW7psEh1s8HRkm4MGECNbxVR-6Uo4WQ.cbhz0-D9ZeLCDgL3.8MqGKQqS9EHKBlt0E0jGaQDmk6N3L038pHvU5a7KHSR8YTFiWFZQ3cODX0Mtt0qvVMmoHCSSRBiIguctq0Rwg3-RXzAZA15moK6aQjnHrh9k6D22g35gftx4G5RV-sITvael-Cnn1LNSdHFgKdKsFI4UP-pFmsVE1vTF51FoRHTgsJH3jV3Ip9TkPEJ1HBMsYA8TVmT5IyuxJ8kXLnG4qV9noKGQc2U2aJnej-HZCfFGL8YG6oQUE5JvfuzdCc2I5BK1HFzvlul4tRCCr0jsd-jQIMH1970j5Hd3j3zMLvnwTv0ZhD9QV9xnFIN3pgbKlPvBy8x7Po0lVcXc_sPFFeY57PnQGKLIzX-Va8jKEKNCMGaNeWkCJfpmjQeCGTwWx_ckHB4bxxNW74dugwsTZ5HAYrHpFEchEn3QjHIeyLrBayg6bcHJudN80zJ0MjEiJ160X0X8mXOp.xW3Ecj0Yf4YjWsEshe_D4A
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 97EAB2AC35FDDE8D2F9FAAFC70E8B9EDBB65E5C0
