proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.247.215
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.246.41
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxVHUtdTE3MUVIZVIycFFkWXhQMUFJaTY0ekxwSUI1VHlDSDg5b0N4cXowIiwieSI6Ijh5cERuc0tOSHY4VnI4czJ1ekVYZ1pzMzY0dVhDTzcyV2VpbzZCT2JOZm8ifX0.nUC2LPGNKbXeJgsHAxoU4-WB2diCXbE5a95h9p0yfJas8DSK0qwYdg.0IVqK9hkff7knEiF.PcWWZDGPj9As-bDQGxqenTookD11G4MjtpyE2d2DrGZ13YbqUuRutm2t8ZrGtgq7eNDFUKd4Npd1i3FEvh6tLL9UFNFMe0NszGyj6uTtzXnmFrUiFN_wGIh0NTSFK-HxDN64Q2MLm60g6qpSL7XaQjnv_VFHo5YSZlhU3MXC2L_gYyIrLCuTAHK6LyTezBrMmg-L0WrxW38nOL8C5kseqjFpc0RpccvIKXcJtI1NmcDjUfaOgDDOQ55_LuJVRPB9bAvaL_VYwBJjQmyLEKddn9Cnw9PQ6ERTzobUeWLMXsqY7CEkZ_uRvaZ8uJ0ngal68hDhrVxSSyhiOQB90w-N3_xpRRi7xjZHG8eIMpjEn5zpnhTa3an4KXmDNbom6QNSHwl0KWuW5SXjL56Xen0QY1kSeVzVqVL4fj8Cze9JJiqGvghxGsULYi3aysdOxx9l72nrfXqKx1M.q3-1qeIQ4Kfd9_zFNA-xzQ
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 0956D8039FE2974949C7CB430468482CF72D7702
