proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.247.7
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.247.81
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.247.6
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJSkZ0TUI2Zllmakk0TG5WLUNBOFZGMUc1cTFzX1BnbmFpekhSNFhnLUswIiwieSI6InNrQ29SSWs3MTlYdGJnMnJueWpLUWlJd0tOVEZwOHhXbkxHYUZJSkJWMGsifX0.E4ZoRdBTcXpvz_vO0kY4e_3XrSF6rGHoUys4JoYIVCD1DTUvWYzsag.EB4xipZflcsU0SRc.pKNZDva7HrgIWzNmH4mh-ucPI20wr0ECISLeUx8JpN6FtfjLzWJT6YDNIw96gCWJ8KmbsQt-kUZx3I5d2VYo5zg-GF1fK4s-p47F6JDDahG2I3phqXGMw7Bm3APLiRLY-VKS-GMPhk-8Ztxo6Sjbj_r3KqHklt3m7M3Wz6EBNb1dMQtzEl-z_dAJ8PdRGvxMOz3eWRRkfXt0y1XWtNfWzLbOZbZJua8RckC9aU6OPrBi01rMDTBH7LrW19hJ1TNCNmVItnYMsm3buKagDh4zqK9LeocCFN9fMnJKJ43pe4guTVN_0eLhw0p1a8_MRFUiEeNvyf1GUBkNJ7e6cW39X30Ua4pYX5GCk2lc_IOF1VgFO6DNS5D7VXXOnHS_m1Rvlq9jck5yyzz-i6uu_ZR__7jvmaRjbt6QvnHLN-TPPtV6241g94PQn2ZWrtY9hhBEdT8ZZxUdUw.XmZYpyg_pap1iPKiqHJqhQ
  port: 443
  server: 77.111.246.60
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 0216C4C9284727C892677B1458FA97468EEF7707
