proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.247.250
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.246.51
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJPclBSUkR1dnNwYXJnR0M0dFVYQmQ2bnQ0ekl5dnlBT2RvRk5uY01ZOFRVIiwieSI6InhZY0xzd1ZCZFdZZHRQU0YzWUpjSlllMkF6WW5SNWhSdVpQR0hxNHBKTlEifX0.vk2qP929Sv1RoApXoM_ca_l6ux-yrWCur4CZIH9RbnAoGiPYKV4vrA.45UdYXgVPRV7_HOW._XphwJ2lXcpSMC8lQd79c7JZ91pj0Y-PtIWxAaW-EmpIsuyculCX9NFyjP3OS7APbGSitnmExC1mtlmyN8F8sBc8SdAhhjURHJbAIYv-3AmYvkPy99ajuAO03dtmYo82Gm1uzrHxtTWwnK7zhB8dzMp6GIdd1D7vPyxt1Ay0FrgFyVRev4y6O7TDNiI7SMavv16gEHEeDXg0utPHp5SAkZhS-plU0oiKlBQBKH6Wr1VdxoZlzAsh9L5esFCaM-y9PLLLJuilQ-hhiqZydSjcjValVTwFM1EzQv24_4Ov0vWii55RMYKGuhXQhSTM6aRn2dnbq4QXmZOt_qeEdK-n1qOASUUyIyT9JnNfy9MkssHq9HhKw0Ri0YdPxJwYPiCKg5ezIBVy5wNlXhaTT5TODhrHqkbOe_j_YkcFC6rAZ6fd9JaAz7J0nkBW7-IDiLqC671tqj6iBZ0.iQ1wX_96Oc3-d0OnOsj6yQ
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 5E3861B86C8070B53198674C50A2E0AC3498FBAA
