proxies:
- name: Americas-01
  type: http
  server: 77.111.246.25
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.57
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.14
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.61
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.15
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.11
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.17
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.214
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.253
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.58
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.55
  port: 443
  username: D5CBD99CA41BDCA02386C1CF51CD4CD60E2EE321
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGM083el9fY2hkUXFuYXlRWWtTN0N2WHVfSjA1ZURVSG9fZzF4UHk2SFBzIiwieSI6IjduOVN1M1hObHJaUEtRQjFFaVFUQkxGTWRkS2pRY0gxSlhwMkJsenZhT1EifX0.oODx04hU44nW5w65p3oWMML2MT4z9wSMZIbYH1pM_Zy_uZEEydgy5g.gRmC0fE3OtTe_Zp9.1XFm9HHLGQI6_aDpYyGiyWsiBeIAx_UR72E-WgE_cKXpmy2JIUyCLnxvLl-FXrYrwPEi03ad7MZIu5ovzZ_tPfvi6riqHNMC8J3oNH-UrZg9ScSHAwLYuu6iI1ggVejutXD3keKWhhn7uU8doPut7-lASbVqIUH2XzKytQsCvLfqXr_YfCimExzCjYc-dDSejsFK9lP7qRJu93gXWVjf0UKSvPxnMxTlKtwppubJHbAiv679R0DRDEODsqKcGXwhKK4X-aLKJsqq0WTNMiDqW6oeCSRljbjcjp3QefvK2ogxJj-AYwptSYpm4y-J_chFP7Ay-RkCWf-S3WcRH966j8S4p47mCaN5Fpg4NhAe7B1T9BIhLgP2o9dNgNajBizOzlQL9ScZz8w6YPcDR6prCeEwsG63AhxhXeJtncx8JK-IMf-enbZGtTkrrP_NqT7H5YkrJm1nSsoi.P1KJlL1EsnZqBHRqyRXXBA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
