proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.247.50
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.247.232
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.247.48
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.246.18
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.246.8
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJkYThnaEgyYXUzclVuRy1hTDFyeW9TWjRxcFMtdEFEWjN4eFQ0aUhHdFA4IiwieSI6ImVSazF4bEV3ZDBZMnlCajJ3bS16ZG9BY2ZVeS1rNTFOT0psc0liZC1ZUTQifX0.asEMoXhrYMLWNW4eGFnLIPY1hg02uRj4-rOCQLsGsS7h1GV8gSAOjA.KWCpDUO_loHW-Ts5.gRoEyjuRvEvlLreYH_AVJ6rLyIL8UVSMOcDzOZTvIBu0yPoSg8h_okTRPJaMUJiFsU2NwZZQjHkpWTXvasTzIFrm4wyAmPvxTv2MVPDKQD1BTA-yJ0kS-jmOB-sOFr40XDBw_it3PrCESuVQncywItEggxnAGlxoIm41NpQmam-eSZk3qKNVuvFgjvS0Dj4XIg-Nv5nFr4maKknIDx688L387dwOlIt1IaQB2Smr5OxaOZ5_uH4F4MzZEeuHYe3Txam3Yt9DB7VfIke-uyldV38pyd0hewotsrkysTyWYwtXCAeMnPLoJVWoYQCF8GdnT3bWZkbJiLf_JmX661fHlHB2M7JbzracJpfZqkCUcaBf_zXMUUG8U9en6SFFU8oJ6Xo6Zbu02eRPpeZgUx_SobSUTzAG--kqGlrunVW9lWU0D7E2BBQQ7XXEvgBFOp06s5UiQ3hV984HhI0.8nhd2WQvj74nOe2LodUZPg
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 0449FDE09F111F1DE3D03221E31BE98FD9464C0F
