proxies:
- name: Opera-AM-m0
  type: http
  server: 77.111.246.56
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Opera-AM-m1
  type: http
  server: 77.111.246.25
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Opera-AM-m2
  type: http
  server: 77.111.246.126
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Opera-AM-m3
  type: http
  server: 77.111.246.60
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Opera-AS-s0
  type: http
  server: 77.111.245.14
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Opera-AS-s1
  type: http
  server: 77.111.245.16
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Opera-AS-s2
  type: http
  server: 77.111.245.10
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Opera-AS-s3
  type: http
  server: 77.111.245.12
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Opera-EU-u0
  type: http
  server: 77.111.247.77
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Opera-EU-u1
  type: http
  server: 77.111.247.76
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Opera-EU-u2
  type: http
  server: 77.111.247.61
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Opera-EU-u3
  type: http
  server: 77.111.247.57
  port: 443
  username: CD0A076C1E32FC463FFADA60154E34420726F06A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJpOXNCck1MSEViOGdWek9SZGVDcjZ4anU3V0tLN3B6cHBZNGp4Z2g3bF80IiwieSI6IlZjazJmS3dPdXgtVTZac0VjaGpIOGRTNzRMVEJ1QVVBSnlRMXNiVnd0X0EifX0.puvX76P2JH2qNgZce4U92GiANEU8I0yxTxle9XQnUXN9i-bTwogleA.IXMJrC2OpAidCAWy.J9fH9TnNalWd0QBy8ihYXE7MYtMx5GIVUwsHzG2xpxZLgG0DFdjxkJAv4gNO6dfl_jPjsDKvC6WnbPnNhZ6-6ccjALwlPJ8dMh4Mr4Z4W5JCG5I2efv2NQx7t_sCUEANT_UuTwXfTLzDv0A9O4ogWY1i3loRMz2WBSwAAm0wP6b2m4SeAU-WMui4TisIhpX-p1vgG0Px59VIviOhXTQmsFUo305nZYMZ7FQcGGMibnCOT7L5wulh2M73lIf9txxnqsWwuQmIiMvYOySN3-tvE5zZic8Ubxn1Edo9YnpxFePwC9dg9wBTzJEPaGv5Xk9-Zo9BYsC370McJ4faA5IoIKpa-nZHCqFoof_rEOFip1CQpGVpH44gye-j2fqSUZfLILSFDuYmsgEFKd8igPwgyExcHzY_4l6MU_iwpb9ZquWASiZzVZ6E-CVsANutW7_GVpPbN7WYGw.lu0yfkNtMbBNh_tUzwhagA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
