proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.246.41
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGX2xVRW5FdHlEVTJxNmgyejV6SGtqVUh0SnBLNHZtOEVqcnVOeUlOelYwIiwieSI6IjJ2ZzUwNTlmTVZsTU1FT1l0Uzhmb2lZajhqSGh1NWUzQkl5M3FJOFE3b28ifX0.v9r2IU160GIdaDB05yOAkz7vGeu08Xu89JNHmS7yJ2QX-_Rl3jYRmg.lQnc8q9rp9ykY53K.S7_uBI4MyYOQJ-_TtN2RsaM1MTZqk-uLkuFK1dOLqfvqTgDFjw7ksqqf_TqlKKnjBx1BwGuNL__VxZ2scPSs9u4LBUmKTAUyyFQ3pvZkmSbm4lPu9oxtDveCgimFRMNRA2vJ8vuiMg8P6WKXFARfPz18cR9w6I7YL0Gx7eyOlnGHrfiXQNgfcadRc6oB-MWZmpAEaiBI3KkqNjnsJkN6bgPXGNgziLQxSMvbscr5suY4-033IM-58-EOz2a6HLZhSjS-FKZsJ9vJEP7SWDZW09gpIeH9ZDW4nzE9rSDZ8teeO0Fc-hAVpQ0AiVTnIW40NQKZ2zls7I-a2o4-RVe4RrfMDIQ-pSA6-TQqay4hFtlpcEOoNtBj88D_jiz3S8FO6P1Qw4opkRp-dZNZ5BFGauV-evZUeHwsZ6mpZeMrrzQGa0WRi4QcYR6y-Uq9PQr3t7J6xvo.lcZPZu7d2RrMquI9JUX_Rw
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: F1E6B226CA095938351FFAA5018A1F5C7202B4FB
