proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.247.168
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.247.73
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.247.8
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.246.51
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.246.57
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBODBZMkFqVENQSndlaFdHbjd2anY1ZjFFM2RnWkZ2Ylg0QmJrekJsU0FRIiwieSI6IlRFaFpMem1JNXJacTZhZl9lZ25oZjBUWDZzQkM5ZjRVN3llUEdWdWZad00ifX0.HIk31_kp25HqJKmASK1oZriT6lJdeQ2TK2z-ubOJw7kVZHEWIfRCvg.F7oO6lVRKm8cZEV3.emKKbQuT7pY2wskL1DMsI5DtEq21RwLVAtW-OZ3t7Vp75wVEFsumZVI-AV4QeI6aNHCvc0hbRRVHMBaUZL6dOooAQE4eBzJFkR9CUqac9khAcYlI3osY4jr4e3RXQNee4t3mvXMsPd6CQRZVgfPI70J8BaL3P_ux2UyPZZgU__OYRLwoGrZvd9Egm5EjLhYy3lhfAjdJejbEvQ2shWOtJUmtJwvcatxsRrVolYCy9wFKp0Hmk6vAnRkC8EaBoKRIEvUKeN3PkRn0XCG5zW8A6C4QM56quJ4JeDJqLZ1ackkIgonL3MJDGWA6v4G6SBiZmCD38e_W51yWqhp6FbqUB3nZI0P4A_5kSsxAq7eCvLx0fBlKHxIC5Qu6-WSL7T8BJrrPl94K-3ZvEz9GXc0Gse8JUPMWw7V1bRapy8Sv8s3ekk9DI-_kp-D6UqDbOw4RuAJ6rZAjtEbO.kq8OkdAzV5IFFGS6Sbnqyw
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A052F0C365A8C02F5C9D61EE136AE0504291B6FC
