proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.247.146
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.247.22
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.246.46
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJwaGNLVXNjek9ERzRvcHN1ZXQteTRmbmVDM2piaHpXbklQdTE3MnN3YVFrIiwieSI6IjFqSU00Y3F0RVh1ZnhncEtZTUp4Y2lZVno1TU1BVWhra2c3Vms3eUdMd2cifX0.Km1t3ffnSUl7JzKLzI0-IpLtTt_jithstYSG92WSPOXAjIKzERTq_g.7DPreNpAvlPSzjqZ.J2FWyHxYQUcSOiQA9rAcjkxAW3VpLsWNlqk4aDjsJueiR7-ri5rdXKCeS5NB7NsPLnAViST0N5mdts9csKnFJhJodQhGaikesO8Fdu7wkG7j-ig_n50hWQbqZS4hXoiN-FANrndaXR-LhXrnRaJpb_Ni8R_543odwhkE6CjIKpHK1YYfeqDc_IxjXt7qSdCZRPErIx4LBIOEDkBjyGH0Y331SWLoRQKlw9cK6IWv_xzZJTkkjVCYMQT7uLuZwxRppkZ2NxqVABMT_Z4R6MHijmGkAyLfJkYi2DJvPxPO8AkIzMZMAKZjYokbu5_ynKC7hZ9Uwg_BqPrfYXp3ALTAZQ4wqd0Q32iO5JnnDhfJGFKQI1jZLnm6B_ju9rXi8OsjkqqYX_HjdqdDSExZA3qxpV2uL1V4wywozVkp2Xa2A34l6tWg5mSJo3mFkI-GZMLA5vtV3Z9ipQ.exd4NIS0y1PPLohTu7WvNg
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D19E205ACB323B25FF110A97D010E1EFE9A261B5
