proxies:
- name: Americas-01
  type: http
  server: 77.111.246.50
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.19
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.14
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.13
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.12
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.16
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.17
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.214
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.61
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.55
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.244.37
  port: 443
  username: 8800C8837484A478243EEE836E633829662E4CA3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJYYnJkdmJpdkl5X0k1WmpZZ2hNVVl4NWs5Q2pGRlRCdWxCU0lBU2sxNlVrIiwieSI6Ii04bzQ1WXlDV25MdjRjYTNScjdPT0ZrN3NFaUtUZ3p3T3JLRjhhZGpkOTQifX0.4nwob114Ucjx6JRSxr3RPeibx7k4Kklk7TCEql7M9ZL0b1qVwLUhEw.jFEboPfsEb2I6t89.QUqfAo_ShgkG06wni9jMLENrr-iVo8ZV9_P1fZS7hhFbHqvEqYbHRXgfLBIaMRH3XwMQWcX1TWMatrbRjiq49a2QnW3CnrOLMD295YMNkTUccWEYlTSKqhOokR8v74oKO-bQx3CpN03HIZsT32ISPiaHKhMd2p61xhb-oX41RQM-ZffUVa9_5i5qs7SFWpyfLb9tsem3n9aHt-K60Gtz-Le0OQtpiot13NnHFfNo3qDOMIPr0RQGKPcTHyJnpb3BJbSPd255V7WuJuH-8vGdlgL5ZkuLmuOii2MqK6VeaD1EUuSG1BdCqWtafKvpxcZQ4A6qqID_9k74QOLIaJysU2PpTmCE53PfqBJdCvItNCPEqgXliMaHPsi-AFiDvHC97jEuXq9GuOVL3bVKWOkI2uKcYyNrsXF0Q93FWd342OqkztlqfcS0DM30PK0I8yJqtk7fGva8ltU.oK37JRtWidJTExvbkmjOOQ
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
