proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.247.22
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWWXpxV2drTTJNeWRfZXZvYzBnSTZDcEZFQ3VEd0UwLTdHLVdHZ0JZWTg0IiwieSI6IjVsZmd0cjVqMEpkSWVPZ2QxcnBkSGxKeXZwdHhEcWxITkV2SFRNNGRYNVUifX0.nuVXm6JYniGo7lUL7ct9uGbMVtrnPFqZoWG7CQvoMj2RbCTfxznKYg.gq4TRhsJwSjmiK40.1QRPw38lMPy-iQ2vZfEd1CJr8pEq58PMzPEZXnjP7kMz3bqaBytbYivIuFJ8yzQPUuYhMthCDB6_ZFYndgFFJjI13Th1zb5P72mpelu6FfVQGCNQXIA9QWbapVl42ypDd6Xix1WkOeTCqGiHlXyF58-qoTXhn4k3Xm2f_sy4tnMXHORZ6uij7ZmMEtp9aQf8qPkDWMcICQz-MmMgjWxFi5uC6oeDh1cD30SCJzgapTGap8WlwdFeTac0nDXBAYKMx1zpE3dLP7xYKFmmSAh3Rrgjr9HvdaPZDuh7kn02WzeEzPQvvDl1isFBKcRQLAJOEkgTfu2OSCv_UumndOARNpi0tFNyDnSXwyB_MIptlJ2QSELQ0xRYLnf2oU_RdP6Mz9pMKlX9fvM1o9sokq_Axp40WBgw97G1A7hALgQum5OCy6vRFbJXSTzUq3yQAhxW_jXnWf9FrA.B9oOK7OM66Gd9VHMcHSCBA
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 0010427AE3B6F64DC027B7EE1FDCD5A65E9D0985
