proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.247.7
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJRZzM4OUFET3oyY0V6MEY1dlhOUGJXNzJoSFJPNUhGU1ROUlBWbzJPZ0JNIiwieSI6IkNERFVNRUhEbHdiUkNPb0RvLWI3LURCV3V2TW5IM3piWFFoTDRHc2FoOWsifX0.uWjcvk0RmSgUQEYj9fgM3UU0C8tDiuMP_JgZdVfPMGWdQmEhUJ5A_w.TlypqYvkT9e_pCee.nXCLJycfK3sNwWmbVCnXbpLF9s72tT7999vyFBbOUHPjJF8q8a6LI4MTetx-WMLjOMUgZulNnlYTrKacX6amp7DAN_o81kiGSRmIHKhfM1vSD7Yj100dsolg9KClWjIZGbTSi0sKZ12u9LO4y56NrJFipWR_o9QR0I7yY03pl6sBnVhIfiKK9u2m6NpvWSOOdMUeGMojHuEuRf43kXjmCEsdjpTLXxqRq8Lg8ccZXsoyVRNjU_MSk21N6h8K_NwTKjfnFFXk26xkVZK0ya9SvHz_zjyjU2MaSLwJi85sKzu9wz5FRv5aIvlUBrZlECaUXBoPQMVDtkyG3dz6ClCWfw8y08s7MgXL8u4cNckEO8fItH6DNq6d4P-NPtVe5LuZpA0SKFFFCev8mu_BmpYpeJw2qcpkJN9ar2SYDfczUBTUHMkCucJAgZ8JZnjcWGZVZnY1-9UlTztdFP8.9DKx7wE4GqvgqYtlfUzPEQ
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: FD5F6B12FBB01F26CB6B642BA821BB87EF9F8A7A
