proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.246.58
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.246.55
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUNmY5M0tNZEVfTFd2cDJTa0d0ZVNteEgzV1RuNThuSmhLbFZKVEFaMHpFIiwieSI6IkhuNWlzNEduX2lNdjU1SUZMWS1odW1ZTGxBeUFvOXgtcTVHS2lVdVQ5SncifX0.xnL14Szf5OGXN7TuJISxPvU-eHPPs1mDqboKbI1fR_xSbgqMBzd0Tw.o7c_9vYQvzN-AO2t.68vhIRemqqeQ227aTlbYMoOryuPiPk_IwF9Q4ZnptcC4B-Ab0EmUNH3feBzcCyh8naRrJ_NkNZMwlnsESvfgzTxu4iY1EP76uyJEp9yytW1u3zc-9VwPJl9pYIaRXbd21sUESPyV05Fj2l7Wv3Ho8D-HYLifXXEzEVDU3g4oBR56LCJyhCeFAuEnsRc9LMej0UBN9npSZhkVZRoT1z5etV4W0Ml7bFb4qD-IZgeflBWNSFhH3OKkrrVXXj81klrkMH8R8SrzHgWTRSZIIYm1s-W6ZATnWeMzJUlsUpgvn28pfpD9ZmLmYLyIX5Q5LJExo81Zys8rKDPEDZtco-RH5YQ8S2T9sEzb1BAlglDBlC7XSGHqrt-eVEht5dBqUdGc9YrW9d6cs8T900rVrKuN6sR3TIb4PWu5OiX0MJFobxiqI4yj4RmhRQ7a7FI0o19yjoYI6EP35g.IlP3h0EzNYOVkeMWjdIO1g
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 6A2F4648C33CD6EAE1F0FFED3CC548963A2FBCF3
