proxies:
- name: Americas-01
  type: http
  server: 77.111.246.17
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.45
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.126
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.26
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.13
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.12
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.14
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.16
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.233
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.44
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.214
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.244.210
  port: 443
  username: 08BE3D7A189516B463A0FA0A4ED0C159D4FBCF0A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RW1HTU14cHl2NU90SEhsVjlqLVZFZU95S205d1JDUEFjOVNNbm9YanJFIiwieSI6IjBHbWgtbjNDcmwyWlVfOTBsVGc0UmV5ZWlCOVVHaXZsdkJULS02TTRMRm8ifX0.XscdOgQLuj28FJ5TrXNsXLPJvOJoiYLvlibgLftFUdBL8GAT3-qutA.l2q_N3stmKNRMLX1.fRAuTolMdtqN_bySxxm9ZVrORSijkVZfCEXfuGUaOEXWBe72_aChw_FF5nA97baN7B2DUD70bWauaQ0JZPoaSnZW3oOqXV2a8lQcD1fghg9fYWBEKjbPDqjV-v5U62QGUEBE_VxVRaRSlU-LPEq_JZHS_Ev0VC7AlthZoTLYnnvzs1zKGuy7kW0zZNlEjy5oYVXv3miyGKqeLDW3S3aqjGzS5S5tvcLscAgzDCXj02-OZCX7gx_GQ_cQmWOId4Yl6bvhMPhnljU2RCJhbM-XWoJiuf8GjYsxgdCFTqwiF5CtEi_9NvyJ2RfRaYzXW5zV7AEDF4OQwiWzKpznANbcv0u7j2Tjj_KToo7ie2tCGc4tkByJ_GRMUcvx9j1YXxFeyXqUujxFtti3mi9mq_ct50Qrbjg-m8EQjKneYjH2a7b-3_0GUTGPs-A8lfxFnGw0XRjgfBn0ig.xzkUo6dmMEdo9OY7he3Yzg
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
