proxies:
- name: Americas-01
  type: http
  server: 77.111.246.21
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.33
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.63
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.17
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.10
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.12
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.15
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.72
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.44
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.77
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.147
  port: 443
  username: 21058C0F9E0E0574084CD212E46929341568AE14
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJISzNXdXlyOGRPU2lTT3o1dmtaOUNsNHpWOFNIQ3E0dzN0SzU4QlNzRnVJIiwieSI6Ik1xSWU1dm9aWEZ6R3BJVUpQT2pwWEZ5RE54Sk9LVF9uNWM5TmgyTV8xRWsifX0.-_AhHCE7nEHPPNPOYHfRhTpTZaii9TQ7XMezkEIvCdWFin172DQBhw.ukrhL9SWmwhgZxak.xOpHSd3g1fHBylpOsW9oT7VKJp7NgZqAMnX0_MownMDockJcLbUH0fuvlZT3LPgs19PBWgDxNr3RGZDHuMj7nh2YRUKHT1YGIP1d0_Udgp5uj6td5-IBdveMAkzfzlihNSLGSfOLZIr_TtvS7jQl2V491gWsjIQhztFTnW6-0eGfzRbS7erI8tAzubXXVf-BmcwUcVbR6zd1iBsRSPEloBS7G6P7Lmwcp8mQCpx3LYvIfvC7OukNwhXYDVy7ivjK_vqy5gg8ys2rSzMashXmriKZF2PiThSzDiPk9ySctDi6fSSs4gS2d87ob1CO5L-wGpW74INexizZkS3UrcYFuW2pUMOAHRiE3GdvrStoS8508KYQl4US9PoRopCl-TpEKxKGYrRt4-Q5N0A0xYTWsRCL_-_bI05uhJU9Zr8tE4_oiIes7ki0f9ENat9eim6nJxW2N7hrGdg_.QVvd4reQEez6DxS0Fmgozg
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
