proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.247.4
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.247.31
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.246.46
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.246.41
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEc3l4b2dmRkdBRzBXSnpGelJfaW9zZVhaRDZtM0g0QjVZTEtrT3VBN3lZIiwieSI6ImszVDdrTjRFR0djaE9iVF96YTJHNU1vNjlBbXljemJtWUhWeENLNU5oVWsifX0.hs4nWUu4GgV7OZq1FXstRfpmdPlXSkBrjcNKY48sUB35eFhvIyxYjg.oy5d6K-J6yUhwpjA.PnA0UCETBtJWezOed7uV0OPanZlxXZOj5LyiUU8kbC62MSQ_CJ207_hZFPmedZ6_95r4npMuSUccJyAXZNP1RML0TOkUIzoTxwZwxcJiuzKKj4Cbzm2AWljqJgviLKPSN3rrym3S62eJLSGmR65qDtMNat7CxfaJ-cD7nbCFTebp-X5S-WEdizFqE0oNuwmkgqbz_LcLGbxqZtQwp32BBewFzvps79_fKcNBZD4TjeWUwocimnacPf_Q9o8sVNusNQsdxjLm16HhevwwRfQvsR1CMS7IwG45m3Z1THsUBBgMPBPFCSBFntsFJhzUrnNkjRClppe3XSCo0G7FbTVc-Xenmy64HmBOc8r6XHxygR1-ni1TQqqxPhQ53LWi89wgBDVHc7k8jf7o4ihbsb3EthIzynp5AboKHYbnU7AJO56sy155DzXxvMDpg3_fDph1yM15_HoAtH6upEI.mjYcPoqpFUj7VGtl3znWuQ
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: B0499D0087A47D22A4FFB7F9F2F5E8338F8E6A28
