proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.247.31
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.246.51
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyNG9kcGc3N0kwTTR1MVhQN0VfOWhFNjlZQ0hxbVMyMnA1eHNrRjZkbGNRIiwieSI6IkpWeGtwN2hkZ2pEQklhbnpKUHpDWnR1R1R4bjd0Y2lSUHJqeUdxUTBlZWcifX0.K7WRGbzf1OBBUuXFc18CE5uXvQkHM9MaKxgjsj7TJ69dBRkWCnGuLw.owKa-2CrDbSHeP_B.zjc-55t36RdZ_Yf68bRC82kEgO8M_NO6c-hLmlq8hBAGW5JkLbgHXrd339iODj6burRGrVJj3dcLrNNQsxiutPaU3VU4L7gC-zAhD2LfgplTBRVfT-H8xWZWQc07hnOc6vSmLIKOumYZSIAnxg1zecwWZy7fVgvtVDn0oFlUZN75SnjfrcZh_l85lkAiZmw9tbdAQUxyXfHR4w6WeOWfn4NfNJGdbSIwPGhX-GWERTYOP61YHZf379ZthBLn045H9QlEeF6e47hUgzmkL_qDLFEsptuX_oHuPrZQGGo_Hw5T3iW-WgQwH8jsGmLa7bqeCs4YvfvK7Efk3dp_OiNXFcJ24okfWMfRPFeCwIMADtAJ8JknmaYOlPOZSXkQ81dPhCEz6h7HRMN3mouafcFYX1uinYKyuT8BdFmSxOpdIF7Cwc2gsYBZ4nYL3zrR2e0jptN6e0pErFgT.G5Xn0NIJCce9A3DOi6t-kg
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 4310128EB09155921A489C1CC4933558A62D2A2B
