proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.246.43
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.246.46
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJeDNLbjlBTl9nbnZ2T0Z0MU9BSUw0ZWIzZEFKY3lNd05oUXFOUWdiQzNzIiwieSI6IlN3ZHpDTno0TlVmSjZmNXRwVVlzSHdiT19zU0tmU1hKQlc2ejdsOW0zTVUifX0.soIj_KGtYCjMs1prltpMkQwDbDqO0LPjHtNQ6g3wmCHHMJAzB3WzLA.LA3atRwJSRTisAuK.23kUIXDRE_wxStqO2Xf-Ltc6HPvCN5Nla0CQ813zHSDRD3zqHiNampckHMAdX1FmP7WPkDpvAv12-pbFHGQhNV-atks3hRrAyNgoS0H4PK-08sv76cD1kGUSyDE49C83176M97qvq3jg2AxxFgls7p3EAGOLo6aY813znYcSE3jed9v4d2wywq_1YYhUiWRWag7DMBEQ7CpvDtdKA-AtOU2RUxT1MoYoLsrnKCApkXc0EuL-3HqiBDaTiU5HRs5NxqKTNAHvT_5M_kdPMPOrKeOsFz6rH-kO51rjAEq7ZNEZxuOWn9_56WPfWTzySsb5_izW5jEi5gn2YV09bb98ahnZbXWdVO97bh4-bAFhLb-id4y_MHh0YQeMfbBJBsgATSIbNaXbj_nKQ3vRy0RiiZfDji1b9xuZsw1nrNDOszNl0353FINjCzKbMVumwrovBC1e11EU5gxM.11dsSs04xF6zGDPNiRCSPw
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 3D1EF693E2F5CB60CEF9A93AD41761AB4F551F49
