proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.246.48
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJLMmNNckxvUnJDMnVEYlduVVFjaDQ1VEpLWU1qbFFWUGg3R0dUX2c4RVRrIiwieSI6IlRmc0VrcTNIZ3FFc3hGR1hVbEdYMnkxVm11LWJHSFBINlI3VDByU3hyRkkifX0.8ndvkSajo47Fhy3meM_48uTyqWBLngxqTd0_QcxVdsKEqEAIJLOP3Q.RraPee1UHGZdC3k5.bUzI-OMM4pgtjfuqeaU0roJHVcl8zkA7Q8WOHbLJzYULoPcx2GPlCvDmcdwX2lOCvwiGK0DPuTHGTqQGG4sNjlwbnOdZbwPLdS0MfH_cjneHEXoOzAEB-T0iAg4zFfzQoefIdv9MTtjLMBJ2TFDtGNm-Zmo3S_zE6aa0Su_sv87QpujJXIBlvCaes0xl9BdlOMcP8FEmJM0-YlKmWGWXEtnFkMmVWne-hlQdPmzQFQR9xA81nWEOZvZFtSNFvFdk4ASVp6dmiPgRAbsTYMRoTA08DFj-gNqHH-vCr5QXeTraooXRrMag8ePDQx5juGvg6P7qZHfwgl10UU6GJQJIvW4M_pmLMvRzDWbsZrIyfg8TYcKtSj0CsY_hr2Ska3EUznWFKZNhzt0U9TH1UhYZ4juXRGu3oHpFy90Hgv2unp_GnnoPaR-sMBHPRw4ziGS-b_m2OfBMhLc.KZo-4zBIKQQSsBgqLJ8wag
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 4CD360636F2C04ACD1EF3F07E68A657307E66954
