proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.247.147
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.247.13
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.246.22
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsQ3Q2cEhQWVdvd1c4bVQyN2hZZlpMTlVteXdkajRiR1NrbGQ4REM2T3FZIiwieSI6ImVqYnBtdV81d0VaeGwzOFp2Mm4zUlVwU2pOUm9EbE9CZGJ6M0F5QW9tdncifX0.ys28q89xZTGsCo8WbfzzYK4OO_CfK-tcMiRys1lidFO6ObLuBnce6Q.utJQDDrILnLM2oCT.uhLVW3mN87KYO11frUStONyh_nnJd6yRDWmCswSGKaep_oLU4FaRsCPI6YfbsyupQfTsQ-I53MsKQEF69nU4lY2VmgzWdbgwlwitN5wYYaMZxaqHXi9dS5vtBkGM6zg49tE9bFzK9aIMxFFOkqo8Clrq97PD8Y_bukN3pd8XpRgNrJuCEDSjevzN_x57esStKSSkceSO36j2F9iamlqjz4M6v5V1785b3pUuz8v1H-QvUz83uyhXmmhfaVtH0xJ2hPsa1QPdE0yYUX8mDWCVpiUbV8PXkPuhK8ySVMWF40hrK24QBSs9xSD3VSVWSQU0Pi-04bihVyVyxdo_pZ8_Kgg-Q-yhrJNP1YLo38l-8TKK3FosB2dSJHifbA357YsocCtLknLfnrRdhJvTdRqOOOzn6ZkPBzw-FhTC98aE34gsZH3DCOTpvvEbpBAHKr3SjaK5RtMJYuI.jKFVQy_YAdqvhtdKXRA4Aw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 5DF7F47C6FAABD595D42C6FFF3791A328C665CA0
