proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.247.49
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.247.71
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.246.53
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJId0RWb2t0cEY2dGRfWGx5ZG52VWtTbmpkSzlub1pOTkJJdUo0a1dNZXV3IiwieSI6InIxbXB2MmZDMENfeTZRWUxvQnlqTTVHWlFqZEw0THdBWThNT3FCa1pYencifX0.z3WnVKqto1Cie-Od24U1Xgsh87ezvUx2TJO1ST68ueYx6xbSQ3L5MQ.BSNCVkeDSrwvvohq.kogdgjf8RxR36qss_DshttBTUZ74d93HpBlhS7JywCZwdjyYNRNs_gG3haAu5XvSxBbyA8H0MzThJECLUK7HAA-Z_SlnqwSKraKo_DPRstp5d_bUnaPBayRYIR1lFYSV44nhCHJbyjSgG8br1nhkeiR4kxFkzhHuEqrbBJfPWHuTty1tT4q0BemQWvIjdNzSryjxZH78wVgXCgUMWiqMWtIb5RCV3Qz6Wf_94buYiDbI4po6whmYInyi2t9Kx526qNU90QoQQgGw2x-QrYdwJ1RzywuiaKjSIqNPneNYuntEiomTdaT61dbga69A83KYVXBqrf5KjdILU5hFtZ4aBD8eB0lyHm8ZOaWNxXTQsT4Do066cFNAl5Rw3JcrITsjHjsPqsjQfCnc4cNjpYE6QtzEPlo248yOXbEyrH7Y_jfV_sLw_34lwH5R0tpb7eRuaP4yMpOJvOtS-NM._hAVAtk2YgryiyTMND3liw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 30BC161EB1AA75BBAF116D4C3E3F57BEAC566005
