proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.247.223
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.246.50
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.246.56
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI5Mm1FRkNZcjhqZWFhYVBVdkZ5UTlxUTkxc1BtekpERTcxOGRvMW1IcFZzIiwieSI6ImVWX2tWOU5kbGdjakFJS2FEU01rVVFfbWxVVG1kNndNQ0hHRGpSQTliUmcifX0.hgI8555UazgLyex9B1IzNAg9Tk4V4WzJzPQ7fv9zZNoHjH-klulUyA.Hoj7TeVDWeFt3x7b.Db9Emuij9EXZvjOBhIaTTPtcBd3ouJwAqfwRWnMhmF3iIEANiBeTx84Me-QMhzsUzJqy7zcR-iTzjkDiaFAfMXtBVMYD28sC0-2bKANPafTluJnIL1m8pIOvG_Ce8WE3eknwFfBQILgCTYxi7mPDUNPMaZLLUvHZG-PRdNeOu4dHNQiX5hMxjWJgz0N3K0XWPYRlFiO1aywFGClIW4RTi4XP1bTGFzfo-7fS2A2Ij_kGWb0h1alw8-oUuH0VFrOCT1BMxCp_QJ9qZH6NPLcS_U7naUNJtghqgQOLhxeMSHsX2a1t70kaZz2eSa8W61oUKqhGzDlcjFu6f4YnSD41I_wDgLG3Gsw25fkj7rLrZ0OwjcrSiEghtDBVCvtDDN9vIbx_rE1hUFsLAg0yufc7WCOCNE4HvL2IWr0cNt-MXSdo3-RR4Irv5RWdoKT6BMIk3g7efc9gNY_KlVE.Ui2ecHZDtJDxmOcnyawS8A
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: C1A09304352E66BEE8109C63FE61F75D73FCC80E
