proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.247.65
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.247.128
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.246.32
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.246.23
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJmTTM2TU80S2tNX09jRnNsVGh1bnpwTndISTBwQnl1OHZLd25HUGpiV3dNIiwieSI6IkpIb2hIcnMxQTdpYzJmQWJIbm9yRUJuV2NBQkdUQ0t5MUJoUWIzRkRRSzQifX0.vDC1B2KaYpFHa5qUche9gKlm5dWz9xKcMDAxVqJ9Y9I6Mn49q0TITg.JN1oE34wzP6fPwQ7.-Milz7hrpFJlSvsod5l2YB3houCUIlMpcrZRWNMoDo4FrTfnrA92R0om7zjFc_GkdDVBY3bjh67tMh29YgFIWCxffpgRNCZdjegxfoyQU_9wyTF5sH9LsWqLmOSRRI2tfGpygto_GIJtHtKS2rD40FeOf9E5l8M3snHZkPBzz3Smwdyo6OG4fvLuBBYm6h5a0mSrs1lIOwHUPEaut24dC-c8EY5VeY07q1kaGNzUeMuDTn-3tNha93v8IKiFlWg9IHFcLOf9EBN0IZlfnDOTAnglP13hWeX0j0TFhrAr7GtuAmJ30MzSRXulbYcT1NUSViFOW-Y-qz6wHrYxIYAEyvYAs6dnVFVEBh6UsxsF7mgOdFWOyjNS6U9q_3O7bn1L11QIWYGHY3zrvZIv_DfWefU7ZOlUWGhF8DdxVBf3Su1ptcJ_gXzDu314_II8h00bP5IrIoo.oY5_K9K0v6JR2CNk8OHK0Q
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D543935A45018A87E23A06238D0A7BABB1A08AF9
