proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.246.58
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMYmtESE1ZUm9TZkdHa2Fwd3AzU2ZMbzZwOFM1QXl3eGJEbElzV191cHVzIiwieSI6ImpCZVF5U2Z2Tm5lNGFCMEtwUy1uUy1kXzJtcmpKUHphNWZxNXcyOGdxV0kifX0.TsvIw9dubBP8rHLrZaYFw2E37CxjGMsS_BT3x--yHQ4NW77e-gCfTg.Ar0n3GL8XIeCXo-C.RL3Tj6x1UIiNceofVKknE4vFGEDQYaRyXEYQ17k946MVtMg7Iq_GdXK2XMPIDEpYZRryVAkUN_qki9DK54AzWVbfHvswg6BJSnWIgnmugTxxaHltmbNObdrvoscIpKixw0gEKdY-nTTmow8gdBg6YZmwKYI9WjIQhtO4Q24rT-m_UMkVRV_9bksseNtpfSw7A8IAkIPaFQ0LIudkjOi6V3TGX7jfjXxiMglf8YIWevNIrCdbTdsHJZwAQZp65_HxF8Wam6rpbMmqZL7xMMPZk-OPV12KutrQxpTMm0F83do1xt8EYm1qkDcJbc_or36YtQZbOv1YX4soosQer-FBUOKOepBJ_8EyufS8etLo5yzeEhnMhGVf4VQwsiBHTj5wMo5HX7lN5sBUoYm7b5h9sc6Bfn6MvcTIp5av2VYK-D2RLrIN1UTyL-q3XoDtrjJ43OFGhp6GG_lj5z4.1T-Qg3CA_oMo3RkqLjlogA
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 9927BC5D60FE290AB76756E37A33D44219E039F2
