proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.247.185
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.247.120
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.246.51
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJZMENuM1FIcU5rN0NCVThaZXpGY0gwai1FdjhhdGVZcEVwR3lOOVluSndnIiwieSI6Im16WVdyN0JuWVdBSWhFYm1uT2lVTnFZTDlwZGFudC14TUZJb0p1U2xERHcifX0.tBEr1We5MUG5r53a2z4e_sfZ4T2Smz86_k9iDMyxkbipsVxwI8sTTw.dEL8W7DoAVPChYil.Hdi0MwQuCtjakFuJNLOjkgWMuUb0N-zkVIqL0wsrKztx5LyIuyVJ03WWJcR1g7sm0NieUwps7D2ZjWBS0fHyuekJpGbuz4n4hO4mzmqi0hVJAFRp5w4LUq77isWUg7Z8FGzQGEEukETVFeCU-gdoZs9pU-PrfNojGUrUd-PHWHjdQ5n9ESPtdygTy1vBcq4IMx9ecpR_K1qvwvQ3KDXT5nWySdaghCU5SeyqKUICwIe--vn55aQj00UVHBgBUXV8pxQAhxNLRQ-ufEC4lLxBdhAXarK4LtaQOLqjoukG7-BkL4LJM3A-2XZbHeO6wopmwTAhNb567IPwvB6Ta1C2se1Jk1MV7YlfHX2BenZdnKMtdBOyQwhOXCYNcrGEXcc4JfCrxbAqRabyidEeX2bCgv2b1Dhf-0gtLcumT9aqR5CualOBRc1RBPegh34DBB6e8dbFjaH22Nk.K0QOPPPmSwZbYpuCAmNmkQ
  port: 443
  server: 77.111.246.60
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: EFE3F3E6B26E8B190F91CA8950967500F95B0FB6
