proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.246.42
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjdGVYMUdsdFFJRU5NMnhTZS1GdHoxWENlQlFNRzFiTVZXdDVYOWwtM2ZvIiwieSI6IlNJT0NBRkhpQzcxM1Rsem5SMWp3ZzNRcVZjLWljYzlRMUttUVcybFdQdTQifX0.dWqwzOV427XogDHNLEFqhbwhodd67IhjALMBf2Po72vchNQ0pccuoA.X6nni_WFMAeDfhrI.gobtKvmrb0e2HRdAR7QKrtCxYpJsqbynmwJ5yDec50Sc22mhtLboKkLJE0rIkI3tSB7IdjcyF-Hi0Rm8wmxMkCpWV3DEYC95V3heXgHwzaABOuu7h9exgO2Z294oy-NfEsTJVA8kfHIp6FOVldCmdpmRfQVCZ-d_BVXJNPBqMwo20ePLr0kxoCoG4Dd3hZclJCe74UrKwAXLqiXBfr0vEW3xf44YK_AOWvYO9bcldZ5zHGOIRb7Wu_bBmJfxfBmy1s0EZs2m6KRFa_cAa7GeONnNaP8qlWL8Gffl3yb9c3aGHtO9Tiezo1UU7jilWXx58yPhJfhe9NDiC6B4w_2XHzp1nZWNFfzqpdK6wxPbnrDe6EIbCkmJRTS5t_r-8JiB3T7DxuF6zaxXyvma3Y4ALnROQ6tgtRKIwHHaRbCZcb-omxL03aVdvEwCMVWyIgNIguGikLjxeEg.BFm_s866uK9gyDpLkQ-QQQ
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 621A001451CB3617BC0956910D85501C7CE6FC19
