proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.246.48
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.246.42
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJyaEs2ZTI5RUdGSnRkVUp5M19QdzZFSnVyZ0RmSnlJZzVyNmlGNTNqN25RIiwieSI6IlVYTlZvS1d6YUJkalFGN1ZoOTFtOWp3TTItZDZyV29USjd2UWtKa0htX0kifX0.QFpkz2Kh3-ft0l4-WUZn-OGwawtIiPLsQkrFRhRXmKhGc-m17VB0pQ.sDe7cYzxB1bHuGM5.s6L34sC6wPO4gBSchmBeQ3c18pPz47PEnHZX8B023JsGEW5UIBszhD9jE2d-e4w73y7kRqMMRD885T2bBqp5037SjJI0opWQVrg1TjKuX7ZDECyj_9v0RY-QTiuUXpqdUuXbVN7k5KzEYT3SjGJnQKzcbFyfxWKYGvyfiV-mo1I0gLtABqp-kdz4zFCqgJ9rgPMDR5GRhGzrnMiFDH3t6Xr9vFYrmE6Tlku-_RiLA7EJrfpMBq2IycGAo-8Z8eFG7USein6DVg87S_54VXMUBhXGItadNt6tHJ4Tzc8RwmZgkEK9x5iYEV95jDVCG08okrZpn_c_Y2jZumkIJcm2rcWFXcyBc1p4cmcBRLyMyPlmbioDydodldTT-zSUYucrXLkonKilL6cPwYIxVv6jz20M1P4o0niX5FbH91ODpNhI6ucyOvIWZ-5U9Edq6yObB0aAnnG3ZQI.4MrqNby4SOdgmXJ5mxDibQ
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 7B106C17B9DB01D268225C7A70BEDF8188CD6B8C
