proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.247.183
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.247.43
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.246.58
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.246.22
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJGZW4zOEZhWkw4aWgwX0pxR3NkS0lOMklYT0dxRHhCWHNYVVZVZjdFY01RIiwieSI6InZPNXgxQkVLY3dEVmxXeEdUS0hyOGRFU2dYSExLVG9sWi1HRHYtS2F1SWcifX0.2OUaLP-TrvhrnlD4JR6xHn4iTTOvZbWFuTUfbGD-KlUI6LWzaHuqZw.W3-z7AXTR_pRArBl.3rhYxgWnEBVXjYbvaT8cq0StGFDnM9dpIF-0Wlvpb-LysNUtF-4XuMDAyBL6U1kb9ywvAZFLe_nbOQa3cRquomW5I_i8cXqbpf9XP6xGIE1394AiEvQ7cnfVqQ-UhO2EFdlJ4mWi5ssgfoWq300Ny76vynZppCjEB7Co3ahDOlw0Z67y8FBNkt4V9rVYtKXIHhXdZGGXWKPop5jGgBrmdRgZtiD_yfZfDu-2mfJIWaJhSTqJbo8hB_MnY4OSJk9eaRQMNl7w7lwNYfXlTWyIQ91UqlWHPyorxpRa_ZzHmC4fGucjtQPt_cucuJ0yRooNPr_yF6Mt6yOAmyIwSIKgDLiSwoMaohucW0cejq2-ztYgaGywYuvg1Z6yAPFel3UzD66OWnAYueODPK3e2CGkiUslnxt_AgwZluqypfN_y8RgwNTLvivA2m1YcUF9nf9ZZJK4S7jlqxSm.luOAe3JGw0Pt_PncPnLTag
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A51116626262F10D704F97681098749CDA88FD3B
