proxies:
- name: Americas-01
  type: http
  server: 77.111.246.25
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.59
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.64
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.126
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.13
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.16
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.17
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.14
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.44
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.30
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.62
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.46
  port: 443
  username: EFFE036891A6A859CBA32EC1C718F8EF5732B165
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJlc0dNVUZYSXNtTlBKSW9pOThOQmk1UEZWTXZFQUxKYVBZUDBoUGNxZEQwIiwieSI6InoxVi01bHkwcEZhU05YQXpHdHQ2Vm9UTE9LaU1PeW0xamk5LWh0QXZXT00ifX0.ponWAXQisJsLScpRZYoYzx4a3v6-zlZrxkxzGo2MRFbg-pxEnbGxJg.2ErPEEgHHctoRetI.IPWWgpehnO87M6UV24IJTQcZdFHsNK-LFype4B_jUjmyf8zyr1SrTCA5v0hRmfeF5XtEl2C2CIh-dLjz3Qci4OPoGvseTGsPItYwIpchZboy0tev2Pzpci_CrZl9BMHfZRn__lsZhPa8BBYd2hxphgLCieNiYno5XvEys8Fsa_01duRlsv2kIIdztVZB1y_AcxfohtEGkCrM62fBvIIBBogNTbd2qQ_XB71AWKkAPGkI4kuxZrq5xS800VHk-BBLM2ddspUciRxym2q7uTV1kRAoFrYrN7IbVcw91YTv6YzgcHLWmLWZ3TueW5tz3NkCksZM6SUu7HtsgtNrKzCgdHN2ewapOT1h2zyCn9yvAmPcFE4vpPX_n3CIEnSQafs4TmEXBfB2VWOgL5KCAh2HpFypBugppoeJOa8j6VoBUebdt-b2U5VOAJycbL25c50YsJvxnqkvu-HxONY.8FSqtAVIyxKUkqt2_f7Bjw
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
