proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.246.36
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.246.32
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSFotZ3d6NldnQUVxVzZvMjVqcW5UdUZCY2pBUEFKWWIwQkxmd0l3R1lVIiwieSI6IkNvWjQwZXBsRS1QWG9Ha0ljaW5vODVacFY1S1R1SUJxNXZYX2tRQmRiVGsifX0.eeQoXDiXrWATM3kK9u743cyaTFGso8rzavNWBCN0xmXCx-p_amYAaQ.acbY--ZYJRIRNC06.8WCre9zLqISjph9Q1vWjqLZmEC2WEll5LZhxo4uwnj0sgf6jhtv08vL_WT9QypHDfMx3PpMfAYyyBEvBrM1lzgRmz_hnsCCTSVNCabn0Txhhna6dRPAey_jip9rOAzM1gBsKAkkRyJbJ9pS4JyvFGvrqJLjpLLgOK4QP3_Ph0J0kNoWKnui0ZRe8Xt1fkRjcXSJkrp-H9wvfYVwORj_YvD5WMOmtKf0y7oWoTGo3y_7Y-F4bN1YOa5j90Q23JWOCyr8tqXkrxab-znTgiicprue9S-BRGq5Xq6OqUpLgpNHvAPGF9KGMtu3Xec7hciV4qaSYlzLun9PC_g1cDlJrzsVwan2Yh3R9vhPP_ZfNEjK9to9pCgaz13EvrVwEZ7Ta-ty3j5loK4loLxQD8yFm8XFOHr9DhY472ZBP1VYJKKXIi5RDqqoGTC1HPc_g0CShv3eT7RXv69E.dQOv1fWry4ZppkjVBUAbaA
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 1E3EBCDC096E9CE34D00FCF93D8491D1552C1470
