proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.247.22
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.246.54
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.246.10
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.246.126
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJiVlQ5MV9obEpOOTU5LWpmUG4xQ29pVFZ5ejlXbW5uMTlfRHF1VlR6SUFFIiwieSI6IkhHQ05aNXF0T0lrR3h5anR3aTNnQnpoWnI2Z1JFTmk1TF9xUGN1SDZTSUkifX0.95Sjatt8h5aRElivEzMne0n4vrIj8rF-JB7ydhvW5nLMy5Hfj8ufEg.PmNdSFiTSpUAHlmc.BoG_lwIODyt8xl4JijrqgjzXtWiOg3rLcAxVQsfT6NTIqukIPNzXbH0il59dZXEX16YhwoM_HJRqo5R49H8qAE5sCjm_I0ir3F24_B71idX596e636tm-GNYUvoqw38SGbPgWsgWrcfOekLIx80IXDSA_Zz39i99x3dcxjWd8BlO4RWDXLKSGB79CqpgWvqQBfeLPfhGBxf8WluJrBwCGh4S-wxKOLBqfw-LvVweA6hM1Fo2FrK0jPwszHF1VWQHWWEyxp0PUBIKEztQZLJipQ2Efo6M7oTbFHHo180n8Oh3GzJNCv7reJRVJuzAgVEzZfkLsfS21UahCajhq65RfpHLhF1MZnmsvHIM8IaFS-4WWTpgsTBmMTFxlSwWuWj8UXBpsePg7FuayqdQArQZPFdXLM9eQ_3PkKSPYyHjgKTh5-mCbv6BYdMCZgARY790UDOXe5UTew.371qXNYRBgh7mj2PfcRpUQ
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 9DC1C6982D1C0369023D0D696557F04EF72DDA41
