proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.247.69
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.246.44
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.246.50
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.246.60
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI2RERqcjZHSjRUYTZiWnhaQ0pJSGVobWI0bWl3OEQ2S1BDQUdqX0ZmYTFjIiwieSI6IlFNazhORjRrV0NlWWJWZXkyMmI3eUdJSlpfZU9JWHhXSEVQVEM0Tkt1RkEifX0.cmZBIAS1M3iSw5gXIDWmRoceAVQ6m_jrmGvdVjfLAxmyLHZmO8joqg.fFgB0sK7aye9tWdp.-0yMcp3s4UkcFebFHeiwc-CrCwWKluKNE6Za6HnXja4MzzKgSgPU9QXT29PxmUaEfum3ffAgCnkRUSInFtkFp9Rr1bRlim_ctliSY-yChFx6YwJENghoy1TNC9Uwmq2LNq9lfEgzU14db7c6OSFllYhTe0m-Vz1BCDYk9YOWxwnVHMveACi9wZoWi7i9I7rQDKxY_uFSQxhjKNaEv0sDvzq6oinY0jA0riNWIqyQJyWOMzOT_K9k7NTiA_IcwVtmgoi4WNqGvd7xd5-raiyxtZa7LQdv9IFS6e54_JLZaO4AK0iTjGi12fIyZ3MidhmnNs4dbZ6ZABq0wwsGhYeY4gbWC1Ds9lO24xlIpPzXTYz3E2WvgkjwDmeylyiqss7ZeWRd4YTgvvyOXT99E-gQEos6EpRQqj3-xwD3J5ugBMCHhTdQ-NSeMAyfxNp0FQh8tem9AP0WT6L8B1k.GFSFhnvVZHLK4jqKwKwEWA
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: E20F8EEE1D069572FEA63D30DBF1310BF3B13FDD
