proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.247.13
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1alBLX3dxOFdKVFBsVmhiUEJIbXRUZXVDeDBqYnFDR3FpWFRFOU9USUJRIiwieSI6IlJIZVdOQjFqVjA0M0dJOUNPdldQYWZucV9UTm5fUV9uTFloMUN1TkJHQlEifX0.phwRQCrLEDZKYYeHthOBoCVCfE-QGloCMJu74HE9yrnnb5t6ALwzsw.4NqRe6NMFjOVJcAb.8iKZcKomqo4QnF2nintDdJkRPH2zO5i1XiNobLZmqt9v2zFa-zDcemb4vMBEpa5BmPFumLKBOa5JjcDMCyOoAIkbEQc9Yglzeigz2-1r_C3HgIdl1LKvJQcz2ZstR6mK8yhtLtfqkU4zuJ5yXUHjCnW-iamkGj3Mr6o3onlQAo70EQ6GUATd4qN2zyAv2N0svuYWrVtYhMGQ-euYNU2UUjLAZue0BZjPbMo8RkJijgjS5tNFV7zCNe2YFehlL50u0zUSs5n0hsj-NrGBGSl2Oxr2p-QV1bbPExXmUb12gq8eOLJxAlwtoA3uHAgG3YsXsamMQ_gjzW48LYxTqLkEaTgsdO12nByqJ2XbgP1IOyXV8j915c-YMdYjpTMINx-uI21xI1JJKadTBXWZOk9jL1Q3ulOmGJS9gm9-4M_d-TUs6etjJZw5IVAe8ZkF3zLqjSpT2MPlizt_vks.eB0thmyN2_IRLrpeuDtNMQ
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A2370D91DAE09477EC50E9C9A410D05284A38EC8
