proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.246.45
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzQXBMUU9TdTBqRDJmdm01T1JCajUteFA4bFIzbDZKYzJoemVkdF91amxRIiwieSI6IjdRcUgzdWV1cHY4YXBVVEt4M2dIbnNlOHEtR2xaOXU0UzNKYzBJaHNuNkUifX0.j_h0-JBUqKIikZkodwHIDhAIK5XUUw52HJ7Wb2oAZZ5C1w6BhIBkpw.jnuX8fsIpxVTc6Gl.PV3kcvrJ4aYPU6ddEvdPOcQJ95nuw6eFf9uxtNwH6vkA36JHDGirf_EjrgBGLjPwpDx0g3v80sRhxVxmdyXVwVRKbK3079B4QVp4oeSlngDHoO87ZMj999JbqkQ8n6a5jX79KlN0RHAo6ZatY3pT0g7xZGbAxekKzln85xQ5kklW6udVsOO2TGjUzuvQ6-KuSzdoDK2kDX4vYSDUot9w6b4JyY2xiwxaXXJfnixZqvACbWkUBoBgpKUO8fWL5OwomdMqBqusnYpOdyrbVqqlj_oAAit1az0BlaaELUzo8re0FZz_mUcP4zu7oZCBC1RkCfFsfEkYG1Ryb0b4ZASI4WLWc32dgyKpYFQmADwtmfc7KvqzrBVX7Z-526Iy009loCCzWuv9gWUI-1yV2eeZRXruTO9SvWudtbN19VaJB5xQsGYZhVf5HdorBapblhJXqbW4KkPYtNW0aeA.q63nZ-Er0frc_32q0lb4Rg
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D81EB6265A82650C37C9BFE7FCF2B27C8D700C78
