proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.247.73
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.247.67
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.246.17
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.246.60
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqOUlTU2M0MWdfTWFJSENjdExiRUxNVVg1dVZJaWpES0pOczNNektxWUVvIiwieSI6IjdBVy1jaWhRR0ozM01qUVpDRVlJZENWUHp2TXpKbklMUndqWmc4ZFZuQXMifX0.1m2pWEYtF0rh80nOykB7F17KF6KF6oK-xTno6viY4Wye_2NnMAgy7A.S84UBZxHyCM-AxN8.kzzF5zSiVwYJo62fwGqD1a6bAReJ7RKtTDq5ASsZ0T9UeHlYlaxY7G0_VdTBhUuRMkaI2M6bWWro2zB3HrG8rEyTN5MPCRKBQtJLt_wkeSPItOKjrmyXRyyLxinPNhfgccfzY2OoYQ16DtDKnMnKsub3X0Z6gTb1Bjn5Ep0MmcajFgVunsL0oTjleSIwr8p1TRPAZow9chKW6Y99GVzby-NIf7zGtlGmLTIIFAoVKO9YwARO_8H1_gSpWOZAylkg3LENiSWLGEhZrZlJFE9LdgkVUNxRW6oXFaMFZgsRJNnCk5e0OfvcGcfhoH429ec2rTzqXR5R_dRbTmL6qcn8AKQMnkdiU30r3hnqVxoCxthXCvCJsIe-sSobsiQWZTqM4RBYivBIRd5xc_aCDsMY4GsPymlbvKzXoz7LNggD7-88nxkH3uoh-y2qbShgEDI-KeN3C2RPc_Q.D8TqAXiEcTxHF2In1-CzlQ
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D773FA3415B239DBC22007A793606F381F0CE08A
