proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.246.34
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfaV9ZX3FqQVFKRE00eHJKclZocE5ZbmFhN3dhenJhR2E3dkRuUDVkLVFzIiwieSI6IlRBUExZLTZRd1UzN3h3VnRWRjNVSUxmTVl0bE8zUWNvZHFoODEzcWpWejQifX0.meoRpLzaEzdyjOf2CnmpV6-Zv4vteRVTdkQ6Fp2U1j9n_IZYK-yrpw.mn-KhCsCotwL5-Qe.Hfi9NT5QOmA_wyndP8KcXH2rTSS8MfYibP0VPNmiQMPtN9md73WVgBkX-CjuKV6VQmwLHjRhU1yjDL6_WB8h6z8d0spH25gZKw7S-oRnpHMwI4fA1cj_KQKPMcIc7PWhn9buCIb3E51rbCRPivF6BwltthqJThTnQNNn_CUOjSEdMqQPBwOwHulX61Lc5a78tttIE51vGI2ETbKRPQK0SoxacP2CzsILi3f0RQjoxvuJYBfD7V1jWyfuhWKQefm6kR9C2RiDNHHXxYgKPsElDq4w3LfNYdo0jVHcwg9c9p3kVEJj4xmoIMvMqTDBquOBRnHh2HcgoxXkB7mn5IJgtFlR-YJW2j230gMR5tleiWAqeOfvtYPSR9onzTzc13gxA0YXAqC24ZMRZsEL5dBTpwfCa0f_jkXGMb5QboYgo0kjt1ACE5W2EtZfSXygyh5kcrbVRYIAxQU.OSrytc_CyRWvvI6LIqu8Ww
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D6F60EB1913A5C8BCB022AF1C28D52E28D28FB67
