proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.246.42
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.246.48
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUc2htN2FkSkVXRExuS1lvbDFVSmxyMXhsNjJrNnNLWm50MUt5UEJwd2VFIiwieSI6IjJ2RGlQTy1xQW1POTZRN2c5ZlhLZGdsaG1tRkptYm9YVkZzcjdDNElZcmcifX0.1uieSDKJVDwYGs_cDWxiTN_SCzxRSCAXD-Py_TNT76LA4m4rIgTcLw.2eR2iNu0tizBoEJW.NlAOvIykJTMBsq1uWG_MtAtr1CEYTC_DcND9B3SwKdabZYe65uzn4m2Qb1mYpQs7JeKhRGW-ZBSH9XUIByXkLdUsaBGZCdZrHINVrCW-fc57fPYIHxsYrP7ERXu8IWPxvg4rCtwvam07DP1sOJUBoO7TXlkiY_C5rl-stMVfLBYw-np8dStmpBRVyHpA3y1xrIVqLEpDiYI1kJBYoMs56YO2JMELziexMmgffG6CSOGMI1AJhHEz30rVI9GFXoOkMeAyS4kAsga1eD1bzjWV5yX6lu2cyLLpQcGog7bPSl7o9P5Rel3FpU-0-NuMvIvGK0RbGSBBze8YwftuccvxEBQ43ujTkkYBdnDKc_NsSQJvU9IoEQ6pPtt194Cc8tey8rBW0r9VL-HaJgV8U7WcMS2YoV1WVkD5kP33QvCcNVx2vkBzZxqFhC8tmvSs93g2CY4ErxIY8w.tLnNa8-HiqNTvMy2MvENjg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 3F54B429F0129D9A616A57755782CFAACDCD22A6
