proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.246.46
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxZTRBWmp5clFaeWhqOU5nRHg3S0N0cDc3OE1nZ192NkM2aXlaTjduaU1nIiwieSI6IkFtX1p6bVRzMVJDeTRES1pZM1Itcmx2QnJiVVpCbXNGejFPY0V4STNLYVUifX0.WYkH9BUl5cYgDv4DI7E8InNVqJN46pp1wSW2SO-RLfZJBUwLjFVQ8w.0PLy2V_29tDib7qg.efkFM7ffOHhv198Dfz6lPkmUst75WiEkywO3Hkx70406UpeKRtQ3B-QvuWtLUwDdjv-WWRGyLzgBLe3suyrZmJqe-v07-ueukEg6y6URmtW7oWNk2b14U2fcQX3qW5K0pTA3FokyTJkC5nq9RCyKTB8l1FzVfmSjaapG8s9ULYI3WCQSKHU7jrutV5vHDNQarPgJSBBrMMQsRudI62iBpgt9noTIzYXpBS-Un659OIwf-HrX8XFsAKqFmHrPZl-mSpwy4DzHcAI2pgPkAaxOlIYJKvFmKVQeWJ1jKaN4_I3OX-gKZugfwkQThs6hW4NhXwlp6mfajCkc3ZaB7ugBkgs4FWIa6c-eFrp8EzubS5tlQS1d9y_VAegISBApLLedCNwEmyaJdQEFfMbQJVeDxfpdhqAC0mSzy81eoJaLQUJ1US25mtu95w2AcXBB4vHnxgywowik3cxx.ov2RO9oE-D4n7L7ejqvmlw
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 066F5D1113B15209E16E666B8416E93EDA657BA5
