proxies:
- name: Americas-01
  type: http
  server: 77.111.246.25
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.48
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.63
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.16
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.11
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.13
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.12
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.232
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.62
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.45
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.76
  port: 443
  username: DBACB2907A44CFE21BCC7336CC29EC208DD1BB4A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0ejc3Z3V4MXF1Vjg3VEl4Tk5yQzBfMlhyNmhEeEdpSXo1UjZWTkVjeDVnIiwieSI6IjN6YUdYNjloZ01EVHhiYzNUOHVEMThETDhZSkhEaE51bnpqY2ZMekduT0kifX0.UXQO17a9BdfUkSpcEsb1UBSBhJPWisze3ejxUlxREDBMIjhV2wVxkw.3tn1ZWIaAdIcaRyY.z7NBQbMOvsHoSEd85Dh-wVMQY3j-2NDsPuWmGp9H54fkfsZROYYaMnWojwk4eH0KwLV2OOT1JMYslUiwuZHIQOQq2ftP7MQzYowfs0g3r2Or33XlaBwhFKlAxciFWZHCS_Z7AxOMS_hhw5MYgCS76KtULJHN8quagK44t8RSswByV5duAv6uVHpoM7MZHywRe8BEM91tQ7xUTySxNBES0FARRMoB4VkpfNdw9CX41YOz3SReBi1CtVtJoAAyer21_tzRdHmKPIIwN-b1lRFLrlE_0sCFSMcTYboOsLRyMwYYI4JPDAiPX_-tnooJkZ9OZQRDd-SiJDhaAEDEJwXWZ_RelGZf-Y0KUbWflGCnMm8lIOLwI_XxEShHBnZNj5HWfKQ-_WwqxVgNSYHKehWRdv_tYL7nzuG6GFBmk3FsTQZiElGO4l-xjqb9ds4byHrEZ3GltF4xQiI.c9R3n_DvDOA8BX1cHAeQSg
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
