proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.246.19
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhOExkNF81SS16cUF1XzdpTzB6SFg3bDM5a1JXUGh6cjZSY3hnZG9iRUp3IiwieSI6IkF5bE1nMzFOaS1GOVZhd3EzbmxQTkVWYlZMRmxQXzJkcHdxOTJmWWkxcEUifX0.9vcWumYWfwG1nzxEy34a0R9c_vFxBwdoupGUn4ZxUbk81ZmLGXKtoQ.subY-PqHiaUpqP7N.wrldDiaM2Igvvs2Ul2md6s4j86IPJM-wT05dMTS-asQnA3IaDntOAY9MBNZSlniFVKzYjupDGr9YN64XN8K4BTHbfk_6-fce3yVPauNs4cajaigl_NdBeIL1vmuj6ChIyCvpzi6D_KOrNJhb8T9j_K2CZaa7Al7C0ublADlcEh-vl02pT6PEqCt3o9iZBZBc4m_552KGbk7roPvcJ-JyGl_kqwg0lKJFu0UcAKMKAJPMA-ltReIU9DwJlldi6JUyr3OlSptHpVMU9QEvjpb38k5_PeoDEBWeagUEWjJAjIT4kiRZOVHZzdOl5IYj3zHCOV6pth5WXUot7yWkeDk5NzI7cITuUcoaIWQAfLDIv5714zjHJD1cakOxUi9xPbf61747QvUe18MA0ZDMrBw6UjnRNP1pExSSNs5NSjirExXvr57Ei8UQ2YNx9hHFswoZdVE7TqItc6kA.PkyYi24ukodzTGZh_1rMjA
  port: 443
  server: 77.111.246.126
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 8C681663913ECEA4CF24BC7395EBF3558C432C7E
