proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.247.138
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.247.75
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.246.21
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.246.57
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJfdmxJaXlqTWVlcjFucGRoTzYzbXJMOExYVklfS0IyT3ltOHZKNnJWajhNIiwieSI6IjVmS1NZb3p1YW54OExXVnNnZ2hJQU4wUUUwSjJsVE9vQ1d1bzVLNjlVYVEifX0.X_P7tVdu5kp3P8yDLEI1EFeK49LsQ8tVw-0Z0LwKd4jU4Qf_N8UOmA.sQ5askK6jljY3vwU.tUKsqRSSopPtSsdLKOFoFSxBWZssdS0wCW3B8haGfY4jGe5eRdRq--GZD0QhVBoYTarA31SUZm94Bn9egegCKqZ7T5qipmKLYQnpl5oswghP8tWwGA_jaa6G0yHFBCLXeGjMeOc5f5oHbels5Lnwkm_2iZjhId_XxQqsGNGMgqP_Ppiqpd1fbOjtHmoVVKESEzA8xfCr0Ahz9DSWyets08R1SqAL653D1XviY8YvqBd3KBxXgw4C-WycjExZN8A16tU1WQt3_hO7uVej1nRhUDyVIxS3K6PaI9_iA2zf_r9PGxtIpBE8QuuquOS39fjwoOAssLd3qA1C827H9EoMWqksJwV2BkHD4gErPWGZDJHjHEVSlbys8YaOvhXrFrt-8gtgpnPe12QQ1DP7TQZKTuL2Fvwfhnx8ClL-S2XZzFTrx1EvQLFUBXCvJnp5HHi6R6u27B9dqg.dKGSfZ63CpZbUXQtn4bWIg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 1BECAEE50EDCCDC8989D7E27095D6AA12321AAA0
