proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.247.81
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJTOUpjR1FvS2RzcElaQS0xTEduYVYzVklNUm02a1hmaVc3QWdPelR2SUh3IiwieSI6IklwMWdQV3FfcG9QOW1PQWVSVEwzYzlOSXFKcVkybHc5QVdIMlBFeEtIdm8ifX0.NRdE0Dk8sMff3RjRp05Bk7so-Lyqp-beQ2Yn9bDebJSyC5ZjnXpgCw.KYSY8ZlQkoczYp8E.-RlXWWBmFzYVujyeUz06im3a80HkbFPU6qPNtQRwpOKH1Kocavx_MGda1q8AdWaFlMgRghE7L5rUmChoCwvt5A5zY4RV8P3mUjT1JVLfuvZkKWytaoJbKlpzoYciuXgU6BXypK0Lo0hwnUmDAlqsI7MpLqXuTkVXhYeFbfeB1nf2LGoPw_eUb_-aeg797xrvNRM_FPKWLsJNyA3-kKs_omeiJjL03a72CjfLKSiXa_Y9C9EKQqZmj0SdPU5TzpLE44vFalsw1b4GXQr9tZ0aTyDVypqrFCr5WJYdHskYEaf0Pc8n9ylNI6lcqTOpJQ838SYjyCW0CT8W7QIjtRH3xHyzky5PvSFOJzHCnqTnjAqKJSzgb96FAo5ZCL4HK6bNK8w5gGGGHC_N8xABIwHN5pE-hAXrZxwSGYE2YEw6WR3cGwf9cUrSdByxNnkKfulrFzHS49UT5wD5IhM.ci5l85c7jVxWkyNxnuXZHA
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 8DAFBA8DF36A1BE7D5971B649EBC67928B9ADBBE
