proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.247.60
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.247.250
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.246.34
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.246.60
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJJUWIwV29vZ1loUEFtcm9wXzZDdm9pOUx0S0V0Z3Myc0pLQ2FiakdUcFFzIiwieSI6ImxPLWtlTmNDbTk0NHluRlllTS12a0xJUWlsLVMtcVVpckU0YzNhdU5Pa0EifX0.ahd1kiktKESXfCcclyHm17Fjaas25It1SpATArDqD9Gfde5Ookac7w.SFhtvYy_INiDnwKk.CIYC7T0LkAk0jGzZIeNTD1b-3K6KmG98GQfemLhxQhsQbo3EN1GcQEIwaxXoxFCKZ2nsud7IlGFdr_27PfYI768vPOQjmHM-nZDHMBIfVWHGltGuH4lz8xEzWZCyPfdTieoUCMtk_g0auj9mhTjxU8Y-sHRavrvzVA9kH1sYOCTkCkfpFQIrg2zdHmptIpCPSNyUQc9aqOWAazEEk89pimTbfJ0xsUiNsOWiCG29MJyeOTyQnphmTVAe0D0M7FPakMHGJqm5mYBO_zCFfC70GT7wzW6DVyvc_6QVGIllXjd_n9QqAAt6zmnw7wo8sLpFBRp7631pKpjgvZOnSfXPQDnP3qOd3eb4ZOQS-8fCvBBYhrrGGBc2brtHkCdnkUjj6vtVMhvnqcOLN2R8hatVjYRn2rgSVnRrpApUjdgxG0-_2GlSMt-chDZWc9jyypkfzVL3hJOryhY.hdkMVBoBDjxlgGglBpgQaA
  port: 443
  server: 77.111.246.126
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: CD3955921902564235B752C2F41553FAC85C2317
