proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBYnRXRjdEaXI3V3dGdnZKaTZ3NU9XR3hiVHJQWVlQdGM4ZXRvSzVQTFZZIiwieSI6Ik5XTGNSTXRqRUI3RUhHeU9FZTZaZHJSMEFBYXdGSWYwZ3ZJeFpkbVZ4MWsifX0.KnnHWRs99QzqJFLnEdxJ1uUkV9CLMIHm3ZGmq91tO2xSNHe4WV3zHQ.mFBlCR2UL8j0ic0O.TyluKJjU9s_qNK7IHJIMdzUcy9SPj8ARr7oV1fUy1T7PTgDsh50QWc_aAF4GVxodcSSG7X8UX5bU1TJ9L8gdbPNhrAS_cBFUQh6kbTZtVf7R8pztYuNanjX1lxvRHcuaOYyfVNMNmRu-OAqXk9vvY1TmTa1rpLHsK6IBozyplniPbmsrLu6diP6CtkXRaoTbS2BYY55FxbGZy4drUuxtox4wvv42pBSf9wanuORekj1NiTQLa5pzshtn4egJ4o5jSPGsjbCtm6VWEigbh1zcDE31UfinKlmqwR9O13gYmW5NprEHwkg7JyTK3PjX_FXR0GaWo6R1vkhSMhqZtIGVHz7gJczlxTttcA3VVwXoI1e2Y_HFufSJFICjGW5exY-7nFi_ixqHf727R9EfZg3liBwtEeBLkWmP0BeLNn3Zwgh0FJ9fDgPleXn4C9hoU45MPnn8BmbVcZn4.BIha8iDfmmcGCMow9TZ0Yg
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 401237C63A4F5A6B7DA109997C7D534ECC4BC3BA
