proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.247.232
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.247.117
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.247.147
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.246.21
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.246.55
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCSnVfcWZWM1dBRzYzWWRoWmg4SnktY1ctWklZZE01X29KNklFQzZ5aTU0IiwieSI6IktzaXNsazhjWml5MXRabnQwNVFVTk5YZTNxakc5cXkyWFB5bDFDcENFaW8ifX0.Sr87e1pGerxdQZHbqKPZvuJSBNBXellJBiKfxVLN_d8FwBdA4kaTXw.iXNDX7uBF5cWL5Q2._hh1hzYVNQs8_klT7mJgcmIoyoREhDCXCwmZkY8paqzNSciojLuZFgAbubnG1FiYQjJClwIDxj34yBf84_stUmP_9Ny5e0o5akuOuORamluCPBFZsNMOePT3LEjYxwZb1JYDUUBNnENhTrscxPM3esNOIcGhzB6FOtXgGyb4Dv2Vh-L5CRrjCWCIjjMX4gOPkvoEXE4s2HgkrItZo-G5JEMWgj8uAeTql1gGLlS4rEeSFj3G0Uh2qv2hb2WAhAhDOmn7TPFTzi_1jIkB9GPwa2zSOEs1Jno0zuELZSeSYu8u4CljSPWGdpXgZcqNFzs6kjhHj1ZrprdBseyweJs-ZY_bkty8tc-xQO2e-E0-zYnsebMM93Qpql3NtlPql_5qc8EOiwT3pwanUdd6VnNX4lVGul0Npi_sRWT7-wkb0SPDUWAh5za1Aat9y8F1Rn8qA-gephL2CIA.xjFN6DOFrhvVfL6aG_bLiA
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 3A437C306BD1F138EB7D9DCCE046EE16A4BA97FC
