proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.247.215
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.246.22
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1blBHWXJ1bjRiTXptMmNubGVQVTZ1WGw0NlpVU0o5RXhBRU5qQ0YtSlAwIiwieSI6IjA5d1hta0Fna2xOaVVnS0FNT1FPMnZYZXRKMVNZVmNhUGZVX3pqRk0yTzQifX0.nDSr521Wplr_oGWPzVWCNtSRA9a6WoKs3NRVivWVCDNrypp1PPvxmQ.kEvBogs_DegZVlp4.1KlyFFlhWYqwR1CQEhM6NquXIHPxdDkXLM5rs3qnSO-V9LJWM5THJBlFwX6faiwN00oSo0OtaPrGqWcwikco_CCc2SJPLLyuWeJ5sqtF3ALWOx0Q3hfc64ol1eA-0KfCTYjpffRPB6CqCN9wVFRMOK_to3z0znYm_078LTA3O6PKHSJfnBOWU4rKN3b_jvhUYfuHKubzqz4Wq6-Uo2Xp7jzpC_JGN3rZokTnqEt_QI_2pNlB-ZBKG2fdSQ2zA4KzyMZ7pH4Pi38ZbGOxVbZHfAXTO853UamS22kp01JEvSa18pgnhyUTTwDtTDD5BV77notzL1jnbFXJ3Z0gq65vIFSidxE9SurrQvZfdF_o241M9XzMMKy-Oh38jIA8P5goACCFH1o2AlcTTJTG48WOFcKx14dK8v3W1RxPofyYyHnqjAMaACXNcgnK4I-n6RCBl5CUl6g.lrJjns7NcmFFMgHYixlJ1g
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: CFA111B9F26AEB5E78F41FF9324EE79BC15BC10A
