proxies:
- name: Americas-01
  type: http
  server: 77.111.246.32
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.27
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.126
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.17
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.11
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.16
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.13
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.21
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.61
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.244.37
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.45
  port: 443
  username: E5CA26740CF9D1E569D5762FFF722032DF03F55C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJhSkhmSnFaTGItNGk2dVlPZkpvQWh0SEZ3aUpHNDg4QzNmX1JBR0EwMG1NIiwieSI6IkdJQzJzOUtBaW15Q2lkWWdXMkZRUmtKakZRemhjLU1hS2YzMXZHdkdCSjQifX0.tHgaHuBUl0vm_081FJpAL879nWMJxSUkH96tK1-LojHyLoVQo0OGtw.3ofJRadlxTQnOZV7.1E_0XH2xHPLLFVag0v5ApCwEXS6NLur4vPyVG7NVXeAQFyuCHmQA-xPEHMMDQRTosLn8bAxAhELwr9Jt2jy_asd2yXFt_Dh9Zb3rJxVjITuWywMvDeNvf8zc7MTbYosHRKf6KJHxeBaP8DZMaho8FhcxwdO4dvVs_9nJ5JAKaCsx-sxa-RrEIbLZ_sQCPqCVRezbFtKuHdC573lmRi71-CfHx_iojHY1MAjiqR1jusDeDJ7CiBRsOXnJ_Jx5-lF01spEoc3gE9zhU7N3zm08IPDE4boK36kLLV2j9N4jSkwurBf-xurbkQKOcqWenaW5gNRzBkF3OgOhtnqqC-aerOnD79O0F2js3mg8mlwBzM3pvIFCxeWXqeSdSgz1McXUb9hmYu5G48Es5NuCUjDw4Oj7A0e5zX9YhUgRq_pBEjI_Ph_4LAJyiWtMeqKagmwdt9VD5ITTpAUu._BRu_IFobnBkqL9_rET_JA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
