proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.247.117
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.246.46
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3aVlnMlVxT19SQWszcndBdzFTZWdUS050YzRfWW1vZ2RQOFBEb3d4RkxZIiwieSI6IjRVTkdrb2hXczFNTVVWV2VlNzdOZ2dKb1cwTnR6ZUJTQlV0NTQ5SW5QZ0EifX0.U5r1rPfydjyJSrKA4xlaUKCOtceXix09H27MOpT2HSIwkdblErHjag.0ZUUrIbUBlcjl0Z5.eQe5_HteFEXL1FDyGRl9kMPPHt7p_Q-q9SCJNJF3mxDUBtA2RjM8A3qFL6LDcw9TxQTdd2h-K6yZeqar71G6r12Ijx2aAmSlM2nrLtyFE7qyUw3pw3QXBbnI7LpTO8ilg1JxZCcVAWKAvlnvY_4Vhs3mOMSihRByTpp4g5JXridecuWBaH61foWINaYew3j_HS6xGOHD8zPqIKQ0pSwLAh30UXGKdzWQlbkvaQg0yNeHVdzsMsoxXTRBhRVquU2qSJf7Bino7ujB_i9sTurtZqv0W4PAZ-uLctaGQJxpQDageNrIEQk2tfMtPOibTjqRCUimT-ThIrVqCwjjLtQ-H7JO1YaJkgshAiwInXyMEegoRLSKnXgFvu1BcMbDspV9-zPULjMee_i0sprVzwxPmlAn7hLoVoC7Sai6nB_ASd2wuVA_X5xNDcHvOAui94CpEhGEYn4zhdg.XW84p76pGVqUt_DXf0_K6w
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: B99AE9D7A52F9D5B1D99794784B4A3F492C2E6BF
