proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.247.43
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.246.54
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.246.29
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxMUEtREY3VGszUE0xZjFVYk11ZlMxdlE3RDFLeGFkN0FQbnIwSl9MNWdFIiwieSI6InRYbFVCeDVwNTduRGZIN1ZEZ0ZUNnMxRWNwa2NwREFpSGFZNktTYmdPdTgifX0.EQC8BkjpRCR4BtXSl3fmlEuxWicD98njXFFBNREhAnE5-1YgLRk9Sw.Wt4xSDr7fkoKWNG_.kC74lcKSBAzNHvpxCG4pwiouhZeRDQMKcV3gNQ3-kjQ7_0QpwacbtKTdlw-7epFzm1xglr5dBeKrY4uH9eh3EgLLcPWnoePTkbguZw3ImER5TpbwNsmBnnOrSEVG2j6Ko9reL4Ugo_HY3gMGZBGIQG6x3Y6W8xA-uCCEOlMQvPKuEXyJt-uQVHNk_C6lmSX8yl3-KZz71KThxd5iSayjWzBHolvDSZqWq-NfKUMDxzOqG_jgDFVMbvZEMPtoMD0I1cEGa7aG9jFnA0krbc5dMfy5U_JpGP1i3JLehxW9pDzvEzEe7hxg5qs_4RWTgXPS-Yw7ScG51-9bbYUaedDSqlsqtM2ytJJapDqpAjzTkp4FUl94zF75RUmKjMAgCKdRekBcCIkMGkTgfMBdUjhlBn0KxJ5cF2tDfca0V81HMaZmsBpOoYciJwWzPgx1y5JWyVAS7svWOa8.SRpMuQs31hCPxpFWEn3jtA
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: B9449644C99A18DF72167FC7DA6661F2740110A1
