proxies:
- name: Americas-01
  type: http
  server: 77.111.246.28
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.27
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.14
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.60
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.16
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.17
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.15
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.10
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.43
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.46
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.244.37
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.61
  port: 443
  username: 01F034AA4FF03CA42713055F5F886D9CB9848E6C
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJDOHE4SnJhOGxOTTVHZUpnOW82S3NnZWdzbXhSa0NDTEtvbGdIMngxVnVvIiwieSI6IldIZURDSnRnMEtkTkR6OGFPa1FoT0lmOWN4aWt4aUZidVQxYnE2UzNIUDQifX0.PX8xSrrStS5AROTeu5B9pNPIWX5mUlNsZ-Cbj6FF8RRos5Ia7Wje1w.7ps0OQ3Up-Jzpo3U.QIRo10Dfvl_4yYoR-1EBgeUA3lG0kJFzQ3tNDRjuGI-LSBgWzQ_LzSuePHAL3DEzzYBPp3st3ZDrmc7_Y2s4qdHk0cdXY2hBfy_j2NK4VB4iISRMbSB0mHDbnnDXXPg-kVbqJwxAphheCcFjGPDy5GajyN49tjJNvwT0H8N2x3seYT2ZtOTh35A-IZfsGV_EnkJzoqrccpABE8x875sgF0TIRIH47xHEhxe9Otzs3aqKYTU7r17P3e5WHvXYjS5Coj8HRTcGdhSZIuozUJby29-EafBdJDc0Wgokd1-EwQyeBxt-KLXtBxtcsLV9O8XSPrrHiOfBCjYMV7mt0mk62fAhGKI2eZHCpKsqREuIwrTJMgo6ey1IvOyyiikvYT1Hu5lhtJKGmgtjprdEc8M_IIaqLCfRbmuIabgyf_lKHNsF42zAmI18-32ngQ90nKZfEBz1oYzp5A.kuflstUbQJ6tDIXDLMKzNQ
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
