proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.246.51
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJqQmprMXFvRmQ1SlBzc0Z6X24wR2Y3dUYyVnhMamtzUjRKNnd4bnY3UXFBIiwieSI6InZ2X3hPajcyaFNqQUxRbUVzX0ZVdFpyV2FDVVg5XzFJSDNpSnJEZUZraW8ifX0.lWsT8Apdd0Kszs7ExOWt2SGKxvcsbyZN6PiQYqHvsAP6joJ3SfGKxQ.vzxvAMERM64hXF4o.PX7HhodUq_-VXcqXKrnfEMa6oyGiJh1N34zhSf2fgpuFWYkfeSyHjdYf6tjnJL5a866IHJt8NPUee7dDzFSWBYFQy24ytULSTlICZh7L9q41ruTHy_9urNRmn2dlBKmFyvuGhLuxUX_8K9tvviqDckgLlpIrE5WOTolQZ0KK5Z2xTm1JRSkJ9G5NR5jRrajeZttfucEVXrVQdVPKx6SL7Z4mTTcUBA72K0X3X__eXVnlf42W5bIQfydeux7tPistjBSPW6_jZOLAtpxW2ztLouEof0Qid68TxKurq4g09gQi6Wn0AQ_0n2Nn7vrrXE3FHjlabroeQ99zopyWhDt29nFlzxYJa14ChJxOeTSgN9maW3ECnFY2WOo2eBSU9gCqGmqQTqT_ebpddr_-J9wBWk2PdTxXa-kCaa0DxgApVAOgbqf46IwYOJAw1yX4f8nKCy7fh0dcKg.LyxOLKGGytjgCW1u4pvUpQ
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: E993444C7F905618955C09AEF2C7A469FBFDBFDA
