proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.247.137
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIweEM4aUtDNzl2VXJsUlNnS2tnZWxjU05tSVNhTFpnYWVJazNOSmtfMGJBIiwieSI6Ik40WUdJUGtCUUVwcXZHTjdWU0tqZVVWd3RHbFNUWHhUbU41MUtKVDd5a2cifX0.l_9tS720rP9pf0yu9j6CCMdNKi7RV2P9lLunoEZJM-AoNbQKrFFqTw.XjxFZpLhrdG_NfhE.kkvx6ey9PecapszwTLJgo6par7YbMTeYFYOw2Zi5tlVi9h2Ijdb7e1lHv8DPH98OQ-3bLMawj0YpDzluGpU_jruVIDdw-pAOeZZs1ADbfnn_f3STE8vGcqnTZ1rk19mvUCmV_mZwYpcZeaIIw1oYZU_arQH4i8aKYdL4KNJX7SDM6wpuRJn_kryLVg9LMP2FhwyfkGdJlaW2Mi7_8Np4f6ddjU2bLNW68yXXCEbveD2zTbZhOg_VPcn4MAiBF1DW6Le8ooWMve20GAipv7BTYw5WdLDk5SPb-ptpAcwxAZLkdq8VqJFLZJuk-5mWkZ12nG78lT7IOAIohUJsoDoTO3o0UWzsMJS8xGQ3sGW-JbsQG_W-DMOUWIjpF8-0hWGKjyf_KbmsNyp1ay3qa0aIa3kuDu8l1HallTOtlU2H2JksVgpbWH0X3HvLWWC_mo3UqggE2hIKVg.WxplB15cq5Je0wirD-IBdw
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A4CB5B3118FEEA889331F8DBD8B0A0F9BEE05E1C
