proxies:
- name: Americas-01
  type: http
  server: 77.111.246.27
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.22
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.62
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.26
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.16
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.17
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.13
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.12
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.64
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.61
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.76
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.55
  port: 443
  username: 3B8DCC5631D64B124E094DE4C7EE6130C3EC2603
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJWdHN4eGlrTDc3NzhMTlBSdk5Pclo5YS15Ym5JYW54Vm15YXJYV0ZoUHVrIiwieSI6Imt5UnhSdVJVRGtPUDlId1d2SXQ2ZkN5VjIyN1EyZW01ajFlNWQwdHdOZGcifX0.SKAcY68gcfrcW0zasslRMqGn4IGVZJ4KBYqvEQDJpFm87IZXn70e3Q.V0PlidETbFm1pEnO.rh_-W3g5LFVFpneHOENwni4oz1hO2Wicy9xKsHTV_2RW9DklfwZavat2E81bqhHwhIYTTsDHMNoBb2lG9k1l1sZvkVGtYTksveONhggvUmbOPinPZ0IrxSQyxqdnt_00U8eQRoUnQmLdRxb85jDrZ-YNticb3EwgDGhzbQoP8HmpUkq6VIo5txCN4o88lBKyAFqNlss9TNLUuaz7t7vCNVku21CdPOFZpgNn4GTQAWA_vHbFdLDhSQ8n-KGqpTsZViRRQ8CJZAOzcJPk5uqXoVn-_HQdumt-ArZrbGMsiCZM1MZfRA1BmFpxVe3ksYOtzJXeg-r4VK5dn3rDBszoAHI3_39pbQ9dvkSKdLdytqB8Ds_AfZhVkINbLJaj-mracJ1-9kIY5oQwds8c2AE6TnoJAK-OkP9tba3sns1IPr3vNxnD0-Gbd_24OXhH2n11gR3S2cOPWDze.PwmrFtVQRATgz4n_DhKuVw
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
