proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.246.59
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXa1lNUXp0dTFUNUtEbFZGWlFRejlHOGRTT2RhLUE2RWhhNmh6U3dkSVk0IiwieSI6IjNnOTk4RGFoM242ZHU4QWxpd2ZDY05CUElRYjhkaFF3c1N2cGxkLVZCQVkifX0.ftAkOb2oRrIXD3SC-3Ce6PFpE4AYmyP6SVuhjyoHs1unCGBqdhxLWQ.kwUZxEyjNcLFMuZt.CId86hTZwgKsqkvvGcUIO-X2uGm56XR9END4BWHPPNtFHVNgu_B0oMBpLmm8WGy-AoPaIbCx4J7TJDv4U00vgZ8do3H2JdFPh_OFv2NH9wcNkxp1EzdT6Gdtx__tM0Hx8qcmQYx-AujgrP4WPkx72I4DkyxssEc8Yglm11PbkXcokFvuRgLgr_7GT8jc6p_4VYThAjutLg2kz6AYeBubAq4lq3hYMcP8mPxT_JGI_ToaRK85RvLb722eaDvNdE5soTtL3P1Z-gOY1EFbQ6wi97p8VxR1qxwGJO__aeBDxDjOReW_FX1xTXPfpvWm30fDo3b1zFGYfFNMzUQPypeCImg50aE4OldmSYa8xZX3G8DmXGVZEycFgtM9q1zCrgfylEGvWS2MLMoRxoxvpdCyCIu43gRQFRzOPD6Ns03gw2NTrPxzuhMgbBLHzjg7fa9-CQmatzvSJA.VXgEOxvSAbJIHSLmLwNSzw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 63713538C7E405439BBD2355228DA625E8350D1E
