proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.247.187
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.246.57
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJvVFk4YmJBOVA1ekVfU0I0OGR5Z3J0U0dESXUySFNSMXA1cWlKbldnUWFNIiwieSI6IjhDbjBpTkV6aVVvMnpGSDhRbWw2MUx5cTZYOFFGUXlncWNkdlllemYwWGMifX0.ZbeHtzIFQE8c3Om5uF4hZSFqAxE8MV-eZXpUrg5tC-PkU7NJm9Zgmg.NnCz-QMtj_wrRji1.1hdMn2X50_0jY89CCP0ZC4oufPNZL__YGzOrCYmmU5bHjTJctGyE88heocbwrqt_aySShd4BsEuY53TlKdw3Le_j7fiEeylVEbhO0nDAOkdQh1-1YwCA_EfB55ofGtEQ4M5ibefcobUR7iF7EPDjuE7hC1rKYI3zeBapKbyCEczp_0KELxZsbphac0ajW_iGk_16dMUqSFD0ZvCRlT4kdhoHqJKY3oXkMT3JylgfM6uzpoK9Gxe6pHeMUHaF-1_2njXHwYkEVvpRk4vIwtdzvU5JkYPTe8wPGqrrsnezJ1YTAAH2_3ny78sOha4GkmFl2c06W0jNMYxxvLQBtscm1kYhZZHlRrmgrjGZyD11vKjUW5JIhq564c5Op6NSWnnRN5YlR2oi9VEnevseSJ-i41MFoNHZX-xupSiNdKXDxkn-NnB1KIhbjB2INet37zV1hKhiWDNl35ni.x-l2hVGICe0Lbw9Nxf3BqA
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: AF04C2353BBF26D00FD4EEFED8B176C6715A8C26
