proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.247.58
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.246.10
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJFWmdTcUdNVXlaUWRUcG12SVItRDZrdWs0amdsTjBOak5Db3lCbklUQllzIiwieSI6IllQOEJxa0ZJQ1Y0dWttUGNaeWtvcHpOcHN0NzBsSlloZHBzcl9oWnJCTmMifX0.Fpzy7kQOsf7WVw_w6-UmyBPDV0A1EoBj-vgaG_abuAvSEM_jtROYQA.xviL9DiUgHJymtz_.UlA2Wc66ShXgyheKsrh-aEeE9bG9Ngkb7QyWdznpppuYlEGVLvvwo5MRRdEsN8z1LNYhjeDft-hmTszqPK705EmFv48MS2I4mNzc85EiPod057raVCKS_8n_qofdc3h-ENL0ieN7f5z0S0GT-AAGYv_q7mzNXaQ7bx5v7E62nBL_8X1j5sp-Lj2b3ECYRR9mxY5-po3d2ylTi8xbSJW3mgw9D4rr_NKR1jyRFCEiQ13oYxW9R3MTvRNj2QDCbd3hBmWklI-xPmK798DqTMF5wHF3iaosSZ2bkAuSQsLp08uScbhcNRy8tsUCPJL1GmpTdnPJVd-l7JVozJda6Vl9S-ZvBfqcNPSVV57T6TAYaVh7_aM0EHR8qTsA1q5ZhFDikhlqAMYnDGlKkqVu7_SHmmF6FAX9LcCN5-Pfl1JDLPVjAq5AiRkGEhbd4d4QcGqJAsgyJ7B3Qw.mcipwh6ORVwS0SSNSamVlg
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: EF617973A11D6D6650C4A0097C7F4B2EB24AAFF4
