proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.247.159
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.247.138
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0S2haSUIwR0d2MlhlZ25PeEpsak9Hd1JIM1IxR2tlSDRqNFBfOGVJSEtzIiwieSI6IkVRQ3pHVEpwdjV5LUo4UTZlWjJvVHZ3QUo1U3NXY0Y4eUhUU25OVVdwb1UifX0.byfn9QAdnKs2xA_qXmvkDUPoHmYHwysacU-w-iYTZj7r6mfCyvClXw.41dI-acarIdtDFRt.BTvoqhtCQ7mztzW8Qr5I8fcXDvEVw-MmidtEhLWHCiU_dWQjHKSzesiyEJMCY-6cBtYABAYXQa_dDnjtcyCfxinjvh-GdypG1qQtt2SZIN32ebhSmXNSn-uhZYwQbTh09Pa9UdIVDaZhOydr2SW1N8w8nIRbaQHUhuUHFB_i8qU7uSjbGjIHQ4ivn-6xRMiF0p4XMOTOYKJI75UpR5OSrM8GyBY8fmoh6qhsTSOMys9zom4gb2cDLkbT2fgjPbg4mXU_THBKhDjPJAOnl2v9ujcfxNPNvlfTqEhqyOWf9vSqjbncriXubcKUkw0bucQpXuzz8WhCx1K6kKGNFveTCnsDS8tZE3F2c7iitnEHW6qECP0fCZEJ91Q6_RR-7QHpzgxeKEuuhJOeOtXkii0I5fjopRVWn2nObwiNkdL2clJR8BtI-febT09EWTRRY4NVzzbOE8jy_bM.ofkR18nP508QDFQnowo_Hg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: C67502A93C4BE0DD2CB876B0DD3777686EF59780
