proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.247.64
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.244.210
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.246.35
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnTXVvOFpRam1OQS1hbWt5NENUSDdCNzY4ZnN6QUQyYVFpWWNMQU5yQ1Q0IiwieSI6ImhMejZXdzZwOENaLVVwdHVtYmZsODJkZjhaWUpGMlJtZ19YV0tuR0lkSjAifX0.qvY-ZNjXzUVqmyWopTaRw6HALN0A8quzjnBidyO8oDmAAeCxU1wkZw.lDqwo1Jrx-O5o3rA.w1JkYk1axAbdHWQvDgs3cGkqN7VyCntGp1O73j6B4Euu7XVJTivlM768uYHq-VEB-AS3AijhGGttBKcuOr7G4HuA2ysN1VxZ0G94Txq9_I6S5boFmhvOumH9EPxT8_oSxnbXu9dB_p6r7ojzlh5VJVsD1dTEu-41_nELfz2NrwQOP33QMx7C_nMIgg0sUVuufzjaW7LlR9tlFdfXOYvru0X-BGAE9Q_AEkGwTsm3XSs9Rqz2eiwS0RiD-W84hkpmm1ASr4tAnS12lNOaZt3VxQMRHP3fLe_LgXDM4a6azoG35c1bkEVC8O6GmRlW2GoGF7T_vJMYfaRnsxEzXOAOJBMYHWDBxJKrHm9kZ8cHBOVNPgTUGNSxJKu8JENOQk1PDWWcyDxWGov26lV75v3PyDS4r4TQrTtibhjduH9brm9C_lY7RaXHj1lLRWHdguDbT564CDnjY4Q.fmbSe_48q95Joisa-2rANQ
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 51606A3E19050C65464FBDA7D3AB44C73B227039
