proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.247.31
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJSa0ZrdFNvLXZBWEJtZmFFS1BrdENBQ1pZdTMxTDhuT3JvV3M5ZjJWVnZvIiwieSI6IjVXY2NyZDM0Vko1OHc5eXNCSzg2aFJOUGZjOC1fbVVGSG83US1MZ0N5c1EifX0.bTK52Edt2nJmvG73zoTcHyD7Ug-yTHXJgXBHavE3UmB7XaK3m_DQcA.o4ydgjDwu-aeynei.n8PdUPpvjHXO_pQsZpa-WhV0fHaZNAigFfLCSvWa3xOWdJwjAglZldznp6CKPtX3GurKKdyJkzpeXMzg04Hcs9ott3--9cRAmY3m5-AO2HvpVTBIeMDsPwyK109GIk5Ec79F_D6p8HvWqIhGJVIjLZWDBHy9C5w1qdtrVkcBDj-SKo2K7waUQRcLosajTw8GSNAfqyrAdiBaq1560EVf41hTNWWzvxF-upv_iBMt1Dego6NtSx6ST4hCKIluUrI1QxuR2ZPLfNMp8Q1w5pGDQk_5_oJFvNnvFu6LUkOFaGONRWqDYaClgM5VjIVrD64ZotNOHY2tQq6mdstlfaOsaA6urVs3L0JRWu3HBzQ1FMFnTMIbeiRZB2z1Yr5KsFY9zRzuJZj_aOmL7rUNxzDuWtqs2-xufKn1SlMKb3YudmYEAfBf8U01-Tx_KzGj6pOAzPvVhE7TDw.ycrqRXTj1CJsd0eB7No-pw
  port: 443
  server: 77.111.246.61
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: EA3175BE02E1F53DB97CC130311751513955FB04
