proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.247.41
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.247.43
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.247.72
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.246.18
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.246.49
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ1Z1JxSnlkUzF1R042UjlZNVI1OXhSOWpsY3doamVCODhmUHVlRUc0Rk5RIiwieSI6IjlpSkJHWkVLYjNmajl3MWFJRXpUX3dpclJoMXpGNVNnU0N2UlR4MFMwSk0ifX0.bd9zeh9Ms8AC4AgOFiI6Pg5zzC0nEg69fDOp1YCc7j2nYpIa_b0Mwg.Cvsndrk8WJZXNJbg.kheeHStygu8-L13VSxt3jqvFFlweCufnYTVdHghrFr-VixcdjZiZOjuBFofnX6ILMD25m9jRmQlss47b37Ci_HUucTO-tvhz7I00hotxTM12HvfAZtkM_UUx1HW5sI8f9xVzGi6s6izwUOCcXk4ElmrsTLHOGXUB4re-EFeCFblBEGC1x3OsRJjOQK-CplQPvdl46fCqp0uWkvqYnRSM_pAic3JFC9rq0KlmVdynn2tFXSGN508qqPOosvk7nGU4Okg4TrFyWSfDkcAOduKLX5UvsDN_yH0M6IhsoFlFRSb4b_fhVesF7SdXWYQPiT-XdQYUXTkyWisgSg5o6Qo7U2tGROrwthij9EBC4aF1rYN5hP9yDjVw4zYHYlC7TMYnjqGNkvVqDKQlap0RCytzhfb57xYeNdE1a_kD6NU9rzyCXRq9U-UsS_Hiw1duOktlCdvhsNB7MtlmGKE.KOZMOjCbFMPyV4vBIXddjg
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: D4C15930239FADF7DA50DBD2F43E7BA0D6642698
