proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.246.41
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.246.23
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJVYV84aG9rakFtMFhkam1qcGRxMWxDUFl3a0RTcElJbFpBRWo1a0xDYkpjIiwieSI6ImxEdERzcDJLdjRLXzROamhBR1Z5N0Rmbm5QMWRSeG1IbktpX1BKWVUxTUUifX0.ebNszTsIb5ON83z6PsPEW8vejP2hjCR3pA86hUoPg1TpboVpR0ZWEA.43y8o1ETtw18Vvc5.CD233T6UJhx5YY43m8htxRPn9sT9bOmmV381Uw2euxYs9kFLcmMp5MH_09ZeW1FdQfqs-GOB9mjfHRwFQDqhvvwNhXDo7dy35RIftiN0jxx2LwCUbT-9DlI53qTTVU86RfWMMIMNFG-r1KyEOHSUxQYfStATIJukstZkkJtSXq5a-RF6VTIXVrh9EE0nKnW8-HhHPsDsaAmMkGaeiVt8IniXC11oFHsbF3t12An7_JIlCjeiwRNWsJ0bnTgpFc-cp_8anm7o0VeBET28tgpwrifmeun-I3wDDX6Nc4hj6lr1iSV5Dt7MbQCpyqx-fFVRBbFxfBjoSmhy2xRb9sMo8mMGdP17vWDgrqImX4jPsolVlabCtGo3WE9M_4GgMhKkQSn9llpGRNAE-ou1YMux5ziM3RKqMB68ufidXWDQgxAXqgFiOtgCu03urJRYKQFjQXXWkT3FAxoY.p6jLvGBB9dngnncmmVPIHw
  port: 443
  server: 77.111.246.64
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 21FFA0C095844EE821972EF36B38DC39650256B5
