proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.247.50
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.247.233
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.246.35
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItS3lqRnNGZGZqWTl2bEY2aTg1TU5BN0s4a3pwcEhCMHVlX1lnMFJmMUhJIiwieSI6Ik4yaURic09XSmkyUDZpTGN1LVNiaWt5Nlp5bC0zeUZ4akRmMDBBYk83dTgifX0.UyaW42qZqHTjnq-VUVEk5xmcn7ZEBvt6XKiwK-dR00WpiQQW_9EibQ.W5qXWnmsIpvpJEp7.ropZ0CFK5Y25E_cfWwndjD31WKq5afRA-cnr4L631IUMoHxBp5FB0Ra3q8kkV0o_tGcSoh-9ppwzkmNWF_71lLTirqsmrOGprFknKUkGgbenmHqIt_j4ah11q_WkRH42KqaaRPewEQaFF7nt6HmQQx8371SQNU_oAKRvwLDLM0bJKfmfFqjzmmRid5-dFU6w0K6-zArqM_gUM4KLKqbKfL2PBV1k2rK5CEUXvcM4b0ST26FghDiCs32mMRAnRgyN0yqVfN4F9-dKVOWxP46_fWfPGbOf7lDEUdQCtLz9IOCDhSHVZBbZE6rCWTQCeLf3_PB0qFQhDOH1eE_MxDI9oNBtgPFC_rInWICkn7iU-LP6sFXItljghhZzDWNBbz8mrr2cRsaqTFAd5hFkg0JFLhjtnULBebUma_BoCbSKwsvyLPINWh5pqNnWdYYOW_HV41c4McXhZw.vYRwAL6KSFs1gDMuPTpYTg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: FC332BA814E96EAD1CCA1EF85A3905FDF8FCA80D
