proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.247.30
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.247.168
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.246.21
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnZjFwdHgtbnVKbmhzSF9CQmRSbjcwYUdPNnBnUjUzQ205bDBnQmpqWkJVIiwieSI6InhZRWhWdEtKUGJZTVVfc2tVTElFZXZXVllnRW45dm5RVlF5b2QyZGtlc2cifX0.wqvWeoxepSjw6dDU2eHWpjmWfl1GcYfIo-3Hd-ONJyWyi8haV__gdA.-_nG9AJQG53T9TYW.-0SUCoAbKH7hxIlIJjhVMIWusDaJi6vvyqZDdB20nux7o-Cvv177JFNOB4fnkPYL4KmeLc50CVhB62-w9Y089O8GtgiJ15uaD93Y1mD0fovXciWPR-dAIoHRns5dZiEYiKbVtDjhZQeyetDJrK1jowAqlhhxPIZ2Qr4rIvBfoBz97t_6vXIkXWvqnlBltlzfpG0uLsTvgWSJxN7E8T2krSpbNxxRIK4JOUbGUWWdl_DZVwgP01OcBgyyOr7uEctAyGAsNOyueLBu9IyNF0L2HRxHTVwYdn1JdH5Cu7DIS-MTkPspFZzp5o6zCpig8MBcEJpwb7W6PjYLn_l-VElRr4fYF43iKWiX72bEK1px1v5U6nkX3PmgZLyxRLv7EByurD0Pv44WQ0AookBRElB1272DMpa_jx50ebN7yDL4V6GSwgQIf8T3toGQ3wZVmEACfyBwQON5R9E.DSxE7nUPDPSmA6btoNz9TA
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: E9D9919503F26B63684E2B42FAC9A1C76F4F5695
