proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.247.183
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.246.53
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.246.126
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJnMlhjZWZxSmdpTlI1dlJHVXFUai1fUEx5blphcTVZXzdZOTN2eGJxdDVBIiwieSI6Im15QU9RU1RVRnhlUUVObDJRLUtRbjJfZUg5VW1mamFhaWkzSWwydjczR00ifX0.R_E_r4O3UljXGigheiF6sE3TgCJG7no-X7Mn5GA4hudjhu-DY_R1uQ.MJ7Bq61YpNnJJbVP.2PBSy8nI46MJIwWKa8-OJeEh7jcwWd0V8tBLPwHcQVx2SeOeEyMj3egtW1CFOaAd-CZcSoCPytvRe3Yo5BPX-f8A10-UvO0RCgZ0Sg7ibPBvshvA2vihZUPcQGCaAuCt8_HXyfgPYKOKvBZ9ek_3yxern0sTBuodDD8DK1mqXjzbMsG2Agif5O3ONVk_6zlHI-L5sGWSIz8XkvCkeIxhVIS38wcNw-De895MlW3JmU_1zxqOGQNYjBA3qzs9C7o_hMxzITmor1dDqBG4knzenDsleZwVAmlbQX1Q5tkzN93fue6lN9tI9FP2gIoNNk3_IuJqw_20gCRcHqbtu_h4JS4G3cW-c52oBLCOSowqBPTk5Sm14fj19tk539eUEtnQRMNVADpNnmSSLLJAB122xnSaeqEij6x4bKoQxHFICLqEKwoiJf6-hu5SiiJ47euUFRfp1Cg.NsrzzETbz6OY8f9s-1fZIQ
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 92620A6103A7C08C0FE63E0617E31404B0A3390C
