proxies:
- name: Americas-01
  type: http
  server: 77.111.246.27
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.18
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.14
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.64
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.13
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.11
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Singapore-03
  type: http
  server: 77.111.245.14
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: as2.sec-tunnel.com
- name: Singapore-04
  type: http
  server: 77.111.245.10
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: as3.sec-tunnel.com
- name: Europe-01
  type: http
  server: 77.111.247.62
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Europe-02
  type: http
  server: 77.111.247.58
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Europe-03
  type: http
  server: 77.111.247.46
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Europe-04
  type: http
  server: 77.111.247.56
  port: 443
  username: 4969EB7BB4A597F497E783420E0D918D96EFAB07
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI3bElwdVRsSlQ4TDlYcVotcFdxWF9qRm5tWXUwYVRxZk9hVEswNGVNQWpBIiwieSI6IlVDU093U1psTHZlcXEySXVJd3FzdkVGUl8tOFZVVzNIcmNhZHRIWkFtWTgifX0.6SpeTT55Dz95b8E_Eg_WDLGmvHi-mIFcRlZExltvnoeCfbeWMUyOkA.b4ddx58nKgHJcKnN.ez4QuzAOhi9FtwskoOL-VPqOsJvaQhbcXGtQ9H44ExhsaSLy8X-CirnNTvSIMFeB2u9FiQuktifYOpDfiwIJolz87m_R7KWHXCofuUQueTwAZc-F0r3YQXeWwjX9l23jik7NK1InyS6hFhFup2qtJEaVMVR5oEr-l_k55pSngwPtZYGL0-tSoRJk_Rb3rKMRz_AVDQUmYYnPJ9VrUpy2opqIGSmKauqoJeX9XylKtNL4q6ty2dAxW6BY5O0KUuNkThMxAHghyPlS18y2EJWL_tmWm34Jll2nAacEcsXFusWn7205iwhsyv2kHQ45mzIOhehrqYdQho1JIDzDwOFmbwnFucJl29zoUFSTviNnwyUMP2c5kwn_d-367lX4c33lS93LE0-ax3LuFRNIfmKE3h5du0wusa6JpyUYPY17A4mFnnWdBrhAQu8kfRKoroSZrRJg5ayXHw.j_NckV7jLVIypX8FPNKJEw
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
