proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.247.5
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.246.57
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.246.10
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIxUkFQWURia1Z1ZmNYMjNLSTJEMVdCZENDV25SQVBQMms1WFdnOXFFdHlvIiwieSI6IlJxUHh6c2dZTy1GRzBQYi1jMUtxcUZldWg2OWc3SHV1UEF2T0NyZnFkVjQifX0._ktmV8qztgXAJ0vhq1CmWKOuuzcP7qSnhu6mexuXVRZXbWe1APXcBg.Jt7UYLXK7JrTqs9H.dvPwVlDC8n4U3QSqQPnBi-C2u5dJ-I6TcafqlzJT3EPmovU_va5IRqP0MmaPKMidnqOJ4LKa5nT_9sPimDPWB0sRLPuQeCzQY489BXYDSIdjJAi1bNbcinTwQZ3hqE7ucjgdDp-GnHdpN_mdmkDEAUYCw9T0Y9K99TnpwE2CAuHn8BpSC-1wRs_xaCZeNj9nFzJfgw3Nr7XTbHl_ke4zxPdkDSsARHIUjrR--9gVRUh-vi7sJET59ZjCMzwNC7BGfRj90IhhwMYzpUoPB42-TvGA0LuyIkQqxjAsIQVVQZCYwqKu0Bv0OXTeBRuUgvryCa2kvbhtJuSSWRsZMU5JVSNSGd-oyMQOzAUmTsic1HotiDsXjp-VuCPvozZ-ITMkrFk9eG99FaC5iJCw8AE88pQyVJDDq1Vuz4p82Reot3k6c09lEbzdfc_h7oxRHKKo5tN0-byPVf2W.aeaEZOMW7nhJvx5kbOeLeA
  port: 443
  server: 77.111.246.31
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: BFE22523D90C626D8426BB4DBA1585D6C39FE7FE
