proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.247.232
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.247.44
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.244.209
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.246.44
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.246.47
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0bW81NTI4dldwMUlUU0Y3R2pHckZOYnBGdm9ZeHhwZ2dyc2xRTVVmaHJ3IiwieSI6IjRjRzNXR29nZ3BQdkViRnNGTmJGOFpnTDBRZHVQdEJQSVJJaDVYaVNwVlEifX0.YpbMlbeeIxeKqQ2yob4I5FNaOUOSraigyuTEZo7KwhtrLbVYpZelCg.YC3M5EaoN6F9hoV0.BTLQoB4tS8__vuCLRpmOq6WuVXGCk3iPZmtKagQz6jRIy25DAUEkronQWfm7g4GnQURkzLSa9zbpIvGmzfjfn-w8t1pZ0h8RIdv-dYzW-rWwz2kPbABr0Ya-jA6HgHQZpy7g-X1oJSSmlARGcN4nnClk9VC4wjrdeaLEpE0wGke4O2sC14I4iF9lch7Ta_x_Qoh8MytD_sGKI1Kd67_NriOI7jTgMGoqR02qNUdc3tH5mKkZJT-JuNdWYZtX8RL18iJUPCwwwVi3YfQ-ezj1pnuansGxXnvdzhgIhtkIrVlArlnSL4aUNVtSu1F3QSvs7DfgUkvuRTB1c-60E7-Sn7bb29CPGFbV_Jeg41wsuapLNPSbMkVWjejXbLaT2m2NJtS3jYYaBuGLlFYN0pvxkO49Hoz0bQciD1eF1rzQt-AQ-oeYJnl0OwyVyM8_8w3LbDY13Op8UUgS1A0._-rq6T5GGqpqTdxTMc0dDg
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 9E3EFD0D75F9D70002939C5CACB11419EC5C24F6
