proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.247.45
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.246.45
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.246.50
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCRk5TbHlnUlQ0ZTFTT0R0QVlIN095UExKUVZ0OVp1UUtBVEd2RVVfcjc4IiwieSI6Ik9ZXzAxTk5BVndkM3ZTX25lYXlNeE5xcWJCVXVhMk5kVndVbmQ2VlAyZUUifX0.UbTdcv2zQDFPSSL46m7qTrsXggE-xxotJowlf6qK_btICYWN9-uFRw.rUPDipdTWuIW8pcg.mvIyo5FI2lPslVVsCids9s98Y9jgs42WA2nAGThHE0PBYYqoyY_AAg6vQGPCL_z1QnHx2Ubx_V8HWKww8Q95h7CkMrlIOKdBMwSRC7tLGgXjAUwWgXKK-oTZrgQliFEzOY1Getl-kUJLJ9cWs91Jyuc1v7klHKJR43VKOJFu4gnV9XS6hV-0mg8-HvBsbeWNK13rj_9-tVDC6dORLpJju-cm3jnpdRizD4SEZcJeSelwWPQVR1lZvlIUO0Tibj-O5mGAEKryzbQ-o4CRn0BstcETMlC0wtEGjozj6czwEl1JLmSnarLN3x25OIPab9DDgYyVnic5dUM4hNhPje3aeFkcjDa3eRQqPKMHi98SuzbeDPbIbl66a0KUfKFGgH-ARWrHoHH0K3Q-vMUDz7Xb-E8WmP7136IhnKzRpqzs2hcqrU0Nw5_z_m6oIxwzF5hFde-SF-sG_Q.hBYXIAyafn_mEaK0DjlQNA
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 22B69BB03AA1CE220DE5E394A656E36DC2CE76D3
