proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.247.49
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.247.30
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.245.10
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.246.17
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.246.25
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsSy1INzE2S2JSRE1MMmRMV29PU1pZMmExcEVSQVpDeld4b280RXFvOHgwIiwieSI6IjBHY2lZcEpIcTdiLUMtT2loZFZENlVXVzhfSTZ3X0tocnNYajBNbl91QzgifX0.1lj3hqDY0CWf4UhbVALcgcLzP1xqfi43-ooNW0NN6piI_CjxS2RVSQ.AvWuGGo9Xtbgw9PH.TkDPWQJU7cPdOi4dTZjVsBl_knJHX8kghy9V6xj3DkolNRLXgpMUAVOdbA-hNr6VxTorXHnW-OWZX5_ZRwvwq63dG61oqsntumJhP8yLdHi9lNHTOjs7sgjtLFYuJwOaYDcTQL-4yFvDRie6usR27ZE84HEjxkp4GhMq8mUjylztW8of_kVMbuTT6P1G3PL6trfIFZd6K3tFitd5hhh3XK1y7JVBnlrXibdXH4ZtGYJtDZIO2cXpf594x06SoKropJJpozIprkEBdvbOaIwxapbxdpQEWH5S-RuhQDWND1kCSb0lfFAgYyEFpW-sugNTuW9VZeDcX1fYLhRoHzWqVLsedlR5EtcXHuYDw2n84XgXTtmI557OXM4q3eAwmsBegSimWkQnwcLzuVKq1raHXvvwspGtgQj7F9g-X6cvw1hpH7VKlcVy3WpoZLK29ythU5Y9vYtUX0cn.tnFLgq8NQdUXArFJI3m3qA
  port: 443
  server: 77.111.246.63
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 035AB67801BD8D1BB1B541CBC1BBAE732B0A71B2
