proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.247.71
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.247.215
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.247.57
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.246.18
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIwN2dtX0pENDRLYTJuQVpvUktFM3FrRFI0V2ZUSnM4OFZRTW1pa0U1T0pRIiwieSI6IjlUZ0lYNm1NRUYwTUZORDJiVHBmd2ROelV4M3hVN0dreW45cFkyQ0F1TTgifX0.qzKXnvDmj2GkeCVaR0GyybXjGbpSY-VPpzzQzND4Lj_BkfKnyvVfvw.MTYDOPz2IFcRh3q1.aXTjieC-hLm0RAxglbbgsXSsKgkjUFHYvX1uzXNVoQhxTqrgXbG_Esir9WUHNIf_QC_g3KTrMZBti_tTjNj2CAAas8IC1HFVK7GHjGQp2F_sn4eT_y_VQEgbpd4uH4szkHqhrTzqjTP3CdmyNAsFqbE_TWiAw_zEknkpn3X2q4povsyVcdpNqrYUVDSDqFhZ2VkoEjQ83u78wRI8fjRZvwJ9EtIh21bEkwO7T4cY0m-LdOBLnoMh0nBpqHi1Tgkb6u-pa3Chd7PezVoYcmeTrEAQPea4qAlQIw-Lu7DFVnkXd5Hb5FH9XmFJaHHzmDr2-Xj2z76IAQnN6IUGTHpu8ezUrsE_XV5bzvzgjkI5LXChQdvGSbRXR4ymgUMQkah_fs8poS2V4oaROT9mWEMDmMpfBXIqsmusWQCM-G9Dsue9349JfoVdBoJPOhAml9cgCInsXZqGKz8.-cGXQ0JkZ9P4_9OmwOtvzw
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 5FDB503E78BD8CF2C203595F0FF96437CF01CE1C
