proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.247.8
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.247.56
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.247.62
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.246.53
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.246.40
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.246.4
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0WXdsVlB3M2xrQXRPTU41Yk1hSjJIUG5NREJ0UFJERGFUUkNXTGNwbWIwIiwieSI6ImdaRGdfWjN6Mlp1cVhLRG0zY1BWMVZOUkY1Z0ljZVYwOG5seFY1bmJvRVEifX0.zmcbBdbOhSqIvRYsolBaE_trMh4ktG9X4mw6HKXVkdmbWSB1R7_Zwg.-m8o5faXzoj_Bw7L.RcjezZoGNWmsLx5zmzIrqgP-Z9i1rk7s3ITDSoDwmnCgrk7bQALZMwsv56-n9vEUwXtpE_M_BvixvzUY-RTu65AQRIm19MsSA5rXTY1JA6diUGbABzWVpwQv3voyc7zS9yr6soVQoPE1l-2P7lsGke5j43QPqw-8XZb66ui7zCQ5K763eoaFyZXSvwDJt4YXosBPcG7uifT6eZ1OEIwy22GvGse0fWTSy3ih3-9RQckklB8kAL3JcjYfwHb25tEQ_t_gaZOV3RPLOzYOL-aleZTufdq9vw5GwDdcwjz6gzg7UK2nJdgBmj0DqZKpxPB4AWaDilUVvkBYZC0l1dV5hSR28zj3HuQECyfFxQQ1qOu-QRqP0e_6AjsOnpKAaC9cLXG675DgHKuy7pFEtEes5yZoAJf7wJDjIcRCsYZWSxXSsA2n_5TF0jMQTuCEL6bPXQ2mcCo3k9oC.OzwrE8CTEiveukUjNNQlnw
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 8D26FA4B2A61F5C0B3B458A6F9F5CC5B22E26E84
