proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.247.31
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.247.55
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.245.15
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.245.12
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.246.28
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.246.45
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJOT2gwWkM2UGo5bnBkaERoYUM0TVFJWTk5SnZnMURWdTlJV0VLYWp0WlBRIiwieSI6IkltUnVaLWkyUzk1LXJuOVVIckVnb3VPQTR2bGtuWG9MaWxmS0V5WDNWSkUifX0.NSeD67_M5kMamvmajgT71hj9zuEAxoJFRP7p8QFYTcrfvz301NZu1w.vvapT2wg5whwKT5X.LGpNxEsI9n0cH3qjIEf_gJLIWfQ0gOHCwvVy1758GcowSjUt6rMnppQOYGDmu42L-lRBn7AeV9FZdUfBk0ea6bHqC5uf3Xk1GmujO-rkKkOnKi2rwmrufY3cUUH6Z_EAuH7-o66lSF2P2gF7oVinQAvf_VxTRk0Q8eTzw9enrvwcA9OYOBziZ3gtdHDEIP9iCxB9zYWrwqDDu4oCY0Y3w5HaX67pNYCXomnm4UOL0dAbL0m0LubaR_fgOSVaHkv8s3DPITZOI6fRbF1ntKUUgmzhN08Uso-FNGp5BdhS2xYWzaoXmyU0PCOQEkz9LcwF4gUbbYF2g2SiPPP0vutuOmDhpg40IroSy7w3ZbQy2KxG_EZhkTU8saK7DLMajzOh4-w7v4JRqArdEssX0ZglbeBjeAILRRuiUDql3sZZFyZJfPg0M3aqXc0NOpsqyUdKQsbsmANE33A.Y3LbTpTlP2mbGHPywh1uHw
  port: 443
  server: 77.111.246.26
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: 3D843956D883E72773DC3C255D729B0CB27DE6AC
