proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.247.6
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.247.61
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.247.77
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.244.37
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.245.16
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.246.45
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.246.55
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJuU2dDUmZMQWdsZW1ud2pqc3JKQjU3b2N0b1lza2xIOFI4dnRkV1A0OVgwIiwieSI6ImxYSy1IWGRlSmF4RjBMcTNEaTdFSldFamM4aEVMeE9nRXNUdWVqOVg5bzAifX0.P7OoGudhf9Wco9CAVfs9jT_3wLZIKPlvslk6uz52CxNswQ2d0bJlQg.YKArLmj2ZFNcN0B5.wfYJgGE1DTlPh75qYvzw7ZLXJE17VFHO6ChYUquwYACRp357VmbSOtOnXaKIdL0UB9GQj1KFx0weAE6Z9oF1-8eRup3eRApTtskebobpbEmVDKwRx8BqkIalUnWvG483WrYLb-SJaOz7moWSsOif1XvRE5e_YMJ8S2Wb5ktbe61GJvkmv9U1ChkVAT9Ta12e-3A2ECrlUyAivPQ0k5HTTqXn_pewvdH2LS2W6fQZdsMa3a4bAt1-NJB8rbSKEWrFOYCdqOH4ZS4ZxbCygRIBqI7CuvggBmC_p3ehLIBao-HQ3wCqbrS4KzcavGj01tb1en9PNROl9G-IWBpCZxGhfJBjpBWgR_uyZtSmSIKgwl6TqU3j-U5U-ASEfBziYcqal9x64rpxo0hXRglSsTIUT_vdWx0Zx5sJ2O0msIwp3WVbNUd3fj81kuW4AH2CKPtMQZI8Kq-irXZlpy8.4QBKDaYgYbHW8RI0niumvw
  port: 443
  server: 77.111.246.15
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: E42524FA08B3D3C124CA3B9FDDE87E8274665C77
