proxies:
- name: 挪威-eu0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.247.12
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 挪威-eu1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.247.68
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 挪威-eu2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.247.46
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 挪威-eu3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.247.76
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 新加坡-as0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.245.11
  skip-cert-verify: false
  sni: as0.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 新加坡-as1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.245.17
  skip-cert-verify: false
  sni: as1.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 新加坡-as2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.245.13
  skip-cert-verify: false
  sni: as2.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 新加坡-as3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.245.14
  skip-cert-verify: false
  sni: as3.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 美国-am0
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.246.27
  skip-cert-verify: false
  sni: am0.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 美国-am1
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.246.24
  skip-cert-verify: false
  sni: am1.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 美国-am2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.246.62
  skip-cert-verify: false
  sni: am2.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
- name: 美国-am3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ6dXVtMTJERkVsRV9mQ3FkbTI1V0hiZlhqQXY5R2RoUEF3UFZycWo0OE40IiwieSI6ImpGcW9TQV9vRnBfZ3pBMGl0LXJPN1hadmFLVFBUWHNhaHFIMVBVWVRiX3MifX0.lT9S5cnTL9XDH5MpK_54X9KU41DS-WSbNM4hc8vR9YJU0DBdSN7kMA.FaTuvRG-AX-hYPyA.YGxw4UhLpN6E7A1wh3_nWAWZiYHtBdqsZYaneqLnqJ-brCgCWaUT1Pt4ZwCKyO19A2VneQAdeh-_DpT2ib8eXT1JcRZ-0pSOYL7r5FgmaUoQcmjQJbzTEX-vSi7YLXo4AH6jxPDKWW1_EhLy20gXeir6NHcfisJ9Bh_tXw2mJYpfl-HVyG8Y1q1PKW1kGvb6RQMFw1K42Zst6ZZwx9aBy1Z_fjR7P6J5xKSI3em9i6T-EJjeyYCC8b548qa0aoZv1cz7By0Kg672O9YrXiRXA6T2VBFwOEJB0pRyGvMRNO96GEiHOaBeKEGIRc3krw0K1GDLS3ZAykx5Dh6seaMQFk5VrjVssEgMQx7TzYRJVmeTizYdsNrNsHFdjtuzYT7oRVQuuLufSgX8Hv6K04Q1WQoeUUkCzcfN0hPjMlLN-yGkn8oOJpL8wfXpjJXO3JBimsaHZzElqN8.W1scjITKeB0AgU96iMBFYw
  port: 443
  server: 77.111.246.14
  skip-cert-verify: false
  sni: am3.sec-tunnel.com
  tls: true
  type: http
  username: A4EC5BA7AAA2281C791B984471F6172C13A5AA81
